Feature 288
malinink/easy-tests pull request #291
Opened 2018-03-30 21:13 UTC by AnyaMaz

#288 
[x] -fix ignore of "Answer"
[x] -fix ignore of "Point"

2018-03-30 21:13 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/7126082e-30a3-4e9d-bc5e-b560d1316a53) was created.

2018-03-30 21:16 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/7126082e-30a3-4e9d-bc5e-b560d1316a53) completed: **No new issues**

2018-04-02 18:07 UTC, malinink commented
@AnyaMaz merge dev plz

2018-04-08 14:09 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/17353914-eea5-4292-85b9-297a697a2446) was created.

2018-04-08 14:16 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/17353914-eea5-4292-85b9-297a697a2446) completed: **No new issues**

2018-04-12 19:04 UTC, malinink commented
@AnyaMaz merge dev!!!!

2018-04-13 15:24 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/db9f7cdc-2687-4090-95db-a75ba370cdba) was created.

2018-04-13 15:25 UTC, AnyaMaz commented
@malinink check pls...

2018-04-13 15:37 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/db9f7cdc-2687-4090-95db-a75ba370cdba) completed: **No new issues**

2018-04-13 18:35 UTC, malinink requested changes

2018-04-13 18:35 UTC, malinink commented on src/test/java/easytests/support/meanbean/models/QuestionModelFactory.java
> +    public QuestionModelInterface create() {return new QuestionModel();}
cs make that in 3 lines on code.

2018-04-13 21:48 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/9994c08c-ade3-4f35-ba05-287480d170b3) was created.

2018-04-13 21:53 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/9994c08c-ade3-4f35-ba05-287480d170b3) completed: **No new issues**

2018-04-16 12:58 UTC, malinink approved these changes

2018-04-19 18:52 UTC, merged