Changes in user api
malinink/easy-tests pull request #301
Opened 2018-04-09 18:12 UTC by SvetlanaTselikova

https://github.com/malinink/easy-tests/issues/297

2018-04-09 18:20 UTC, SvetlanaTselikova commented
@malinink Look,please

2018-04-10 19:14 UTC, malinink requested changes

2018-04-10 19:14 UTC, malinink commented on src/main/resources/api/api.yaml
> +        "200":
it's a good idea to use same quotes, I preferred double quotes

2018-04-10 19:14 UTC, malinink commented on src/main/resources/api/api.yaml
> +  /v1/users/FindByState:
both of methods should be in get, but query param should be not required.

2018-04-11 05:05 UTC, malinink commented on src/main/resources/api/api.yaml
> +        "200":
Let me think a little, lets use single one.

2018-04-11 19:09 UTC, malinink commented
@SvetlanaTselikova There are conflicts with current dev, merge and fix pls.

2018-04-12 21:28 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/a6ae3650-f46b-4b27-829a-9c8b811bcb12) completed: **No new issues**

2018-04-12 21:28 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/5c15fb95-0410-4e9b-8c64-285674f09dd9) was created.

2018-04-12 21:32 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/5c15fb95-0410-4e9b-8c64-285674f09dd9) completed: **No new issues**

2018-04-13 05:43 UTC, malinink commented
@SvetlanaTselikova seems to be OK

2018-04-13 19:21 UTC, malinink approved these changes

2018-04-13 19:21 UTC, merged