Feature 313
malinink/easy-tests pull request #314
Opened 2018-04-18 20:43 UTC by SvetlanaTselikova

- [ ]  Create UsersController,UsersMapper and UsersModel  
- [ ] Add TODO in controller for methods(wait for table with methods)
https://github.com/malinink/easy-tests/issues/313

2018-04-18 20:43 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/c76059c8-e215-4606-b3f1-40a371a4c19e) was created.

2018-04-18 20:49 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/c76059c8-e215-4606-b3f1-40a371a4c19e) completed: **6 new issues, 3 updated code elements**

2018-04-20 17:07 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/aec3ec92-940f-4902-bc12-d7803699c950) was created.

2018-04-20 17:12 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/aec3ec92-940f-4902-bc12-d7803699c950) completed: **6 new issues, 3 updated code elements**

2018-04-21 15:16 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/c1a9be89-1f01-478c-a3f8-91413457f22c) was created.

2018-04-21 16:10 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/c4309a7b-308a-49f6-bf20-00be9b6ab649) was created.

2018-04-21 16:13 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/c4309a7b-308a-49f6-bf20-00be9b6ab649) completed: **14 new issues, 3 updated code elements**

2018-04-21 16:16 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/d4af8cd9-c381-41a3-947e-838b6d9beec9) was created.

2018-04-22 19:54 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/84efa7fa-15e9-4cfe-a399-54ed3dec8ecd) was created.

2018-04-22 19:58 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/84efa7fa-15e9-4cfe-a399-54ed3dec8ecd) completed: **3 updated code elements**

2018-04-22 20:08 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/29998755-f432-46a3-a9af-3f3bd67ee9ef) was created.

2018-04-22 20:11 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/29998755-f432-46a3-a9af-3f3bd67ee9ef) completed: **3 updated code elements**

2018-04-22 20:41 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/6194ea0d-ba58-453d-a6a5-542287dd49ff) was created.

2018-04-22 20:45 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/6194ea0d-ba58-453d-a6a5-542287dd49ff) completed: **3 updated code elements**

2018-04-22 20:51 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/1f384667-58fd-4442-8459-06b7b27191f7) was created.

2018-04-22 20:55 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/e3fb761a-c26d-4688-8e6c-7101c7a35562) was created.

2018-04-22 20:56 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/1f384667-58fd-4442-8459-06b7b27191f7) completed: **3 updated code elements**

2018-04-22 21:16 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/95740c83-99cb-4f05-b3a3-d620aef2212a) was created.

2018-04-22 21:30 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/c2f64460-47d9-4fea-a3b2-5afed0a5a576) was created.

2018-04-22 21:34 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/c2f64460-47d9-4fea-a3b2-5afed0a5a576) completed: **3 updated code elements**

2018-04-22 21:52 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/e0c53a7f-1e06-4be0-bafa-2025992ee985) was created.

2018-04-22 21:56 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/e0c53a7f-1e06-4be0-bafa-2025992ee985) completed: **3 updated code elements**

2018-04-22 22:04 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/1a97c63b-7aae-42f0-84d8-171009414b1b) was created.

2018-04-22 22:07 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/1a97c63b-7aae-42f0-84d8-171009414b1b) completed: **3 updated code elements**

2018-04-22 22:27 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/8cc6b46b-c995-4dea-ad10-2e71920ff778) was created.

2018-04-22 22:30 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/8cc6b46b-c995-4dea-ad10-2e71920ff778) completed: **3 updated code elements**

2018-04-22 22:41 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/b3326828-9c07-4d46-a1dc-90eeca339a24) was created.

2018-04-22 22:46 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/b3326828-9c07-4d46-a1dc-90eeca339a24) completed: **3 updated code elements**

2018-04-22 22:51 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/cb25428f-0f90-4039-90ce-ed3eaef59f5a) was created.

2018-04-22 22:55 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/cb25428f-0f90-4039-90ce-ed3eaef59f5a) completed: **3 updated code elements**

2018-04-22 23:04 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/64878550-0077-4e52-8729-3e1b1ac53c4f) was created.

2018-04-22 23:04 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/b6b6ad25-d562-44b5-9ab9-a6f2e21806bf) was created.

2018-04-22 23:07 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/64878550-0077-4e52-8729-3e1b1ac53c4f) completed: **5 new issues, 3 updated code elements**

2018-04-22 23:10 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/b6b6ad25-d562-44b5-9ab9-a6f2e21806bf) completed: **3 updated code elements**

2018-04-22 23:14 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/6772668a-61e1-4fd6-b4f6-f4ba29551396) was created.

2018-04-22 23:17 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/6772668a-61e1-4fd6-b4f6-f4ba29551396) completed: **3 updated code elements**

2018-04-23 17:04 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/a7b8f3b8-0296-45eb-b5ab-600a128b35bb) was created.

2018-04-23 17:08 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/a7b8f3b8-0296-45eb-b5ab-600a128b35bb) completed: **3 updated code elements**

2018-04-23 17:24 UTC, SvetlanaTselikova commented
@malinink look,please

2018-04-23 18:32 UTC, malinink requested changes

2018-04-23 18:32 UTC, malinink commented on src/main/java/easytests/api/v1/models/User.java
> +    private List<Identity> subjects;
There is no need for subjects here, remove pls. I've just make an example to test how it works.

2018-04-23 20:02 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/851fc6a5-8546-42d6-ba8f-4491badf0671) was created.

2018-04-23 20:06 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/851fc6a5-8546-42d6-ba8f-4491badf0671) completed: **2 new issues, 3 updated code elements**

2018-04-23 21:02 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/8fcd8016-102e-454a-a226-38f39e492b6a) was created.

2018-04-23 21:07 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/8fcd8016-102e-454a-a226-38f39e492b6a) completed: **3 updated code elements**

2018-04-23 21:16 UTC, SvetlanaTselikova commented
@malinink fixed

2018-04-24 19:01 UTC, merged