Add Topic description into api.yaml
malinink/easy-tests pull request #316
Opened 2018-04-20 10:47 UTC by Ielay

2018-04-20 10:47 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/78017652-a97f-4fb7-b03b-a2a76ca9e2c7) was created.

2018-04-20 10:52 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/78017652-a97f-4fb7-b03b-a2a76ca9e2c7) completed: **No new issues**

2018-04-20 10:55 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/bae6e181-9bec-4d13-b014-92ba96b27237) was created.

2018-04-20 11:01 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/bae6e181-9bec-4d13-b014-92ba96b27237) completed: **No new issues**

2018-04-20 11:01 UTC, Ielay commented
@malinink 
Ready to review

2018-04-23 19:21 UTC, malinink requested changes

2018-04-23 19:21 UTC, malinink commented on src/main/resources/api/api.yaml
> +          schema:
use `V1Topics`

2018-04-23 19:21 UTC, malinink commented on src/main/resources/api/api.yaml
> +        '403':
add 400, 404 errors codes (look users)

2018-04-23 19:21 UTC, malinink commented on src/main/resources/api/api.yaml
> +  /v1/topics:
where is query parameter?

2018-04-23 19:21 UTC, malinink commented on src/main/resources/api/api.yaml
> +        '400':
order responses codes

2018-04-23 19:21 UTC, malinink commented on src/main/resources/api/api.yaml
> +          description: User isn't authenticated
ref?

2018-04-23 19:21 UTC, malinink commented on src/main/resources/api/api.yaml
> +          description: The topic was successfully created
201 should return identity model

2018-04-23 19:21 UTC, malinink commented on src/main/resources/api/api.yaml
> +        '404':
oreder responses codes, 403 also possible

2018-04-23 19:21 UTC, malinink commented on src/main/resources/api/api.yaml
> +        type: string
integer!

2018-04-23 19:21 UTC, malinink commented on src/main/resources/api/api.yaml
> +        '403':
400 also

2018-04-23 19:21 UTC, malinink commented on src/main/resources/api/api.yaml
> +        '403':
400 also

2018-04-23 19:21 UTC, malinink commented on src/main/resources/api/api.yaml
> +      - id
not required

2018-04-23 19:21 UTC, malinink commented on src/main/resources/api/api.yaml
> +      subjectID:
just subject, it must be V1Identity object

2018-04-23 19:21 UTC, malinink commented on src/main/resources/api/api.yaml
> +      subjectID: 1
fix that one too

2018-04-23 19:58 UTC, Ielay commented on src/main/resources/api/api.yaml
> +  /v1/topics:
@malinink could you remind me a case that use query parameter?

2018-04-23 21:16 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/370842f6-e87e-4bee-ba30-056218b45299) was created.

2018-04-23 21:19 UTC, Ielay commented on src/main/resources/api/api.yaml
> +  /v1/topics:
@malinink I recalled it

2018-04-23 21:25 UTC, Ielay commented
@malinink 
Everything seems to be done

2018-04-24 05:56 UTC, malinink requested changes

2018-04-24 05:56 UTC, malinink commented on src/main/resources/api/api.yaml
> +      - V1Identity
subject

2018-04-24 05:56 UTC, malinink commented on src/main/resources/api/api.yaml
> +      V1Identity:
subject

2018-04-24 05:56 UTC, malinink commented on src/main/resources/api/api.yaml
> +      V1Identity:
subject

2018-04-24 22:01 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/2048e0d9-ec71-448e-ab4d-63ac1a07a3ea) was created.

2018-04-24 22:05 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/2048e0d9-ec71-448e-ab4d-63ac1a07a3ea) completed: **No new issues**

2018-04-24 22:12 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/97de7e51-8722-46fe-a19a-6f94c9f2ea17) was created.

2018-04-24 22:17 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/97de7e51-8722-46fe-a19a-6f94c9f2ea17) completed: **No new issues**

2018-04-24 22:21 UTC, Ielay commented
@malinink просто поменял V1Identity на subject там, где Вы отметили, и теперь одна из проверок падает. Копирую в swagger editor, так всё работает замечательно и не ругается. Не знаю, чем coveralls недоволен.

2018-04-25 09:35 UTC, malinink commented
@Ielay please apply changes from last commit 02e9cb5032954770e2c2312788204016b31fdad0

2018-04-25 09:35 UTC, malinink commented
And don't worry about CC.

2018-04-25 10:26 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/0644e26c-e3a6-4578-9a6c-7d76a634bcd1) was created.

2018-04-25 10:32 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/0644e26c-e3a6-4578-9a6c-7d76a634bcd1) completed: **No new issues**

2018-04-25 11:36 UTC, closed without merging