Add list method into UsersController
malinink/easy-tests pull request #321
Opened 2018-04-25 17:07 UTC by SvetlanaTselikova

- [ ] Add list method
https://github.com/malinink/easy-tests/issues/320

2018-04-25 17:07 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/1fdd8ec0-53dc-48c8-8f5a-e4153d7ced48) was created.

2018-04-25 17:13 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/1fdd8ec0-53dc-48c8-8f5a-e4153d7ced48) completed: **1 updated code elements**

2018-04-25 17:13 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/557c4809-d994-4016-bd72-b0a0751bfe97) was created.

2018-04-25 17:19 UTC, SvetlanaTselikova commented
@malinink look,please

2018-04-25 18:49 UTC, malinink commented
@SvetlanaTselikova seems to be OK.
Wait for ACL and test implementation in my PR, than you could add access check and tests.

2018-05-08 05:23 UTC, malinink commented
@SvetlanaTselikova you could write tests on that, pull dev also.

2018-05-08 15:32 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/3f8de2cf-2b54-4093-b18f-97b0376d46bb) was created.

2018-05-08 15:37 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/3f8de2cf-2b54-4093-b18f-97b0376d46bb) completed: **1 updated code elements**

2018-05-09 16:56 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/a050069b-514f-4e15-ba21-5653c5e51d98) was created.

2018-05-09 17:01 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/a050069b-514f-4e15-ba21-5653c5e51d98) completed: **1 updated code elements**

2018-05-09 17:03 UTC, SvetlanaTselikova commented
@malinink look,please

2018-05-15 22:26 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/375b8eaa-e589-4ac4-9b4a-060834b3c9f2) completed: **1 updated code elements**

2018-05-16 22:25 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/584b9a5c-ec2c-4538-b217-d91d707fcf9f) completed: **1 updated code elements**

2018-05-17 19:21 UTC, malinink requested changes

2018-05-17 19:21 UTC, malinink commented on src/test/java/easytests/api/v1/controllers/UsersControllerTest.java
> +    private static String subjects = "subjects";
unused variable

2018-05-22 17:44 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/6bb5ad7e-c912-44c5-b5e1-973b75798219) was created.

2018-05-22 17:49 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/6bb5ad7e-c912-44c5-b5e1-973b75798219) completed: **3 new issues, 5 updated code elements**

2018-05-22 17:58 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/f18d8b2e-8dc9-4183-9ea2-712a7ca8fda1) was created.

2018-05-22 18:00 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/93195ae1-e7da-417c-9d96-2d0881811406) completed: **No new issues**

2018-05-22 18:04 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/61872228-d5f4-40eb-9ebd-52e838d44fa1) was created.

2018-05-22 18:05 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/f18d8b2e-8dc9-4183-9ea2-712a7ca8fda1) completed: **No new issues**

2018-05-22 18:09 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/837d66ca-8a2c-415d-9d2a-4174fcb4a0d6) was created.

2018-05-22 18:15 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/aab0265d-b5a5-4fe3-9d22-2bbb08dc115b) was created.

2018-05-22 18:20 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/aab0265d-b5a5-4fe3-9d22-2bbb08dc115b) completed: **No new issues**

2018-05-22 18:21 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/2dd0ebd2-8de7-4efb-816a-b5da369ffc25) was created.

2018-05-22 18:25 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/2dd0ebd2-8de7-4efb-816a-b5da369ffc25) completed: **No new issues**

2018-05-22 18:30 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/43e6f48a-51bd-470a-86a7-43545ddb3689) completed: **No new issues**

2018-05-22 18:51 UTC, malinink commented
@SvetlanaTselikova Why don't you just run tests localy?

2018-05-22 19:51 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/bfa0f215-f18f-458f-8285-9ec36b434401) was created.

2018-05-22 19:58 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/bfa0f215-f18f-458f-8285-9ec36b434401) completed: **No new issues**

2018-05-22 19:58 UTC, SvetlanaTselikova commented
@malinink I didn't see checkstyle mistakes localy

2018-05-22 19:59 UTC, SvetlanaTselikova commented
@malinink please,look

2018-05-23 18:41 UTC, malinink requested changes

2018-05-23 18:41 UTC, malinink commented on src/test/java/easytests/api/v1/controllers/UsersControllerTest.java
> +        userModel.map(this.usersSupport.getEntityFixtureMock(1));
It is hard to understand that user with idx0 is admin and with idx1 is not.
I think that a good idea is:
manually set is admin to be true or false for each case.
Than, if we modify support class data test will not fail.

But there is one more clean case:
 - add two methods into users support class: getAdminUser and getNoneAdmoinUser and act with that users or smt like that.

2018-05-23 20:05 UTC, SvetlanaTselikova commented
@malinink look again,please

2018-05-23 20:07 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/87834106-1961-465a-93a5-0a98fc7eafb9) completed: **3 updated code elements**

2018-05-24 18:07 UTC, malinink approved these changes

2018-05-24 18:09 UTC, merged