Methods for IssueController
malinink/easy-tests pull request #328
Opened 2018-05-02 09:25 UTC by Yarik2308

https://github.com/malinink/easy-tests/issues/327

2018-05-02 09:25 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/bc4e6b76-2847-40aa-a203-40885b563521) was created.

2018-05-02 09:35 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/bc4e6b76-2847-40aa-a203-40885b563521) completed: **2 updated code elements**

2018-05-02 11:05 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/33abb37b-eb52-47c0-bcad-ec6bfa62ed8f) was created.

2018-05-02 11:10 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/33abb37b-eb52-47c0-bcad-ec6bfa62ed8f) completed: **4 updated code elements**

2018-05-05 07:00 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/24d18671-ed94-4743-92d0-88df6e4fdb5f) was created.

2018-05-05 07:04 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/24d18671-ed94-4743-92d0-88df6e4fdb5f) completed: **4 new issues, 3 updated code elements**

2018-05-08 05:21 UTC, malinink requested changes

2018-05-08 05:21 UTC, malinink commented on src/main/java/easytests/api/v1/models/Issue.java
> +    private Integer subjectId;
subject

2018-05-08 05:21 UTC, malinink commented on src/main/java/easytests/api/v1/controllers/IssuesController.java
> +    /**
let's use short notation from API doc. i.e. list, create, etc.

2018-05-08 05:21 UTC, malinink commented on src/test/java/easytests/api/v1/controllers/IssuesControllerTest.java
> +    /**
you don't need to determine all tests here, just add separators on each method. (so it must equals to controller comments)

2018-05-09 06:03 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/dac2823d-686e-4411-b51e-dcf4cf388655) was created.

2018-05-09 06:03 UTC, Yarik2308 commented
@malinink Done.

2018-05-09 06:08 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/dac2823d-686e-4411-b51e-dcf4cf388655) completed: **6 new issues, 3 updated code elements**

2018-05-10 05:41 UTC, malinink requested changes

2018-05-10 05:41 UTC, malinink commented on src/main/java/easytests/api/v1/models/Issue.java
> +    private Integer subject;
By documentation it is not an integer.

2018-05-10 05:49 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/8704b68f-4a00-477a-b563-509a10035b32) was created.

2018-05-10 05:50 UTC, Yarik2308 commented
@malinink fixed.

2018-05-11 05:28 UTC, malinink commented
@Yarik2308 checkstyle failed, fix.

2018-05-11 05:41 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/6a109e06-4802-44ee-8c31-69c3accd0d64) was created.

2018-05-11 05:45 UTC, Yarik2308 commented
@malinink Done

2018-05-11 05:46 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/6a109e06-4802-44ee-8c31-69c3accd0d64) completed: **3 updated code elements**

2018-05-11 07:08 UTC, malinink commented
@Yarik2308 looks good!

2018-05-11 07:08 UTC, malinink approved these changes

2018-05-11 07:08 UTC, merged