List method for TopicsController
malinink/easy-tests pull request #331
Opened 2018-05-02 15:53 UTC by Ielay

2018-05-02 15:53 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/52fe08a3-c333-4476-b780-dbd299165db7) was created.

2018-05-02 15:59 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/52fe08a3-c333-4476-b780-dbd299165db7) completed: **2 updated code elements**

2018-05-02 17:53 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/2a2fb5d1-8b09-483e-99fe-646ff7b4b502) was created.

2018-05-02 17:58 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/2a2fb5d1-8b09-483e-99fe-646ff7b4b502) completed: **1 new issues, 1 updated code elements**

2018-05-11 05:24 UTC, malinink commented
@Ielay provide tests pls

2018-05-12 21:30 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/3ccedd54-9bd9-491c-850b-7120adca3188) was created.

2018-05-12 21:34 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/3ccedd54-9bd9-491c-850b-7120adca3188) completed: **1 updated code elements**

2018-05-12 21:38 UTC, Ielay commented
@malinink Seems to be ok now. Ready to review.
P.s. My local problem was I just forget about up the migrations :)

2018-05-12 22:55 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/195b00d3-608a-49d1-8bf9-7a4edf2ed1a5) was created.

2018-05-12 23:00 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/195b00d3-608a-49d1-8bf9-7a4edf2ed1a5) completed: **1 updated code elements**

2018-05-12 23:35 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/a29aec95-d711-4339-a7eb-7c5c1b8dbd99) was created.

2018-05-12 23:39 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/a29aec95-d711-4339-a7eb-7c5c1b8dbd99) completed: **1 updated code elements**

2018-05-12 23:59 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/fc3274a0-2335-47b4-a969-8e28f0d8d687) was created.

2018-05-13 00:04 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/fc3274a0-2335-47b4-a969-8e28f0d8d687) completed: **1 updated code elements**

2018-05-13 11:34 UTC, Ielay commented
@malinink Could you check if I wrong in passing the parameter to get request in TopicControllerTest ? Travis writes that he can't get the queryParam that is required to a list method. I can swear that I do things correctly (e.g. such like there: https://reversecoding.net/spring-mvc-requestparam-binding-request-parameters/).

2018-05-14 18:29 UTC, malinink commented
@Ielay It looks like parameter is valid. 409 error code means that response does not match doc. There is some comments in travis log, you probably miss them.
```
validation: GET#/v1/topics#200
2018-05-13 00:19:22.366  WARN 3178 --- [           main] e.swagger.SwaggerValidationInterceptor   : Swagger validation: GET#/v1/topics#200 - The REST response is invalid: [Path '/0'] Object has missing required properties (["subject"]), [Path '/1'] Object has missing required properties (["subject"])
```
```
MockHttpServletResponse:
           Status = 409
    Error message = null
          Headers = {Content-Type=[application/json;charset=UTF-8]}
     Content type = application/json;charset=UTF-8
             Body = [{"id":1,"name":"Name1","subject":null},{"id":2,"name":"Name2","subject":null}]
    Forwarded URL = null
   Redirected URL = null
          Cookies = []
```

2018-05-14 18:55 UTC, Ielay commented
@malinink Well, created Json seems to be correct and seems to be matching with specification.
![image](https://user-images.githubusercontent.com/31778100/40017209-5abf1578-57c1-11e8-87bc-314d3a92b318.png)

2018-05-14 19:00 UTC, malinink commented
@Ielay but in test, return data does not match schema : `[{"id":1,"name":"Name1","subject":null},{"id":2,"name":"Name2","subject":null}]`

2018-05-14 19:01 UTC, malinink commented
If you still need help, tell me pls.

2018-05-14 20:21 UTC, Ielay commented
@malinink Yea, I need it. I actually have no idea why it has nulls in there. When I turn out the creation and use correct string value inside the method it doesn't help.
![image](https://user-images.githubusercontent.com/31778100/40021444-82d04422-57cd-11e8-8fdc-97c09c7d5bb1.png)

2018-05-15 19:03 UTC, malinink commented
```
MockHttpServletResponse:
           Status = 409
    Error message = null
          Headers = {Content-Type=[application/json;charset=UTF-8]}
     Content type = application/json;charset=UTF-8
             Body = [{"id":1,"name":"Name1","subject":null},{"id":2,"name":"Name2","subject":null}]
    Forwarded URL = null
   Redirected URL = null
          Cookies = []

java.lang.AssertionError: [id=1].subject
Expected: a JSON object
     got: null
 ; [id=2].subject
Expected: a JSON object
     got: null
```
Problem is that SubjectModelEmpty does not map into Identity. You should add rule for that.
In simple controller you pass topic with subject, in test there is SubjectModelEmpty.
But! Case with SubjectModelEmpty should work also.

2018-05-15 19:10 UTC, Ielay commented
@malinink Ya, I see, thanks.

2018-05-16 16:08 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/22ca9b64-37da-491c-9276-9e69445d38dd) was created.

2018-05-16 16:27 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/1dae6fde-3dee-44cc-8508-72f592c8aefe) completed: **2 updated code elements**

2018-05-16 16:52 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/2a6578aa-a9f9-4857-8317-543505193d8c) was created.

2018-05-16 19:06 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/f4bf87de-624c-41eb-8906-6edd7cfc7b6d) was created.

2018-05-16 19:12 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/f4bf87de-624c-41eb-8906-6edd7cfc7b6d) completed: **1 new issues, 2 updated code elements**

2018-05-16 19:32 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/ce6e6a03-1072-480a-94a3-8b47273feb4b) was created.

2018-05-16 19:38 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/ce6e6a03-1072-480a-94a3-8b47273feb4b) completed: **2 updated code elements**

2018-05-16 19:38 UTC, Ielay commented
@malinink Finally ready for review

2018-05-18 19:58 UTC, Ielay commented
@malinink Pls mark my PR "ready to review". I afraid you can forget to check it without this label :)

2018-05-20 23:28 UTC, Ielay commented
@malinink Still waiting for.

2018-05-21 19:59 UTC, malinink requested changes

2018-05-21 19:59 UTC, malinink commented on src/test/java/easytests/api/v1/controllers/TopicsControllerTest.java
> +                                .with(id, topicsModels.get(0).getSubject().getId())
1 ?

2018-05-21 19:59 UTC, malinink commented on src/main/java/easytests/api/v1/controllers/TopicsController.java
> +import java.util.List;
wrong order

2018-05-21 19:59 UTC, malinink commented on src/main/java/easytests/api/v1/controllers/TopicsController.java
> +    private TopicsOptionsBuilderInterface topicsOptionsBuilder;
wrong order

2018-05-21 19:59 UTC, malinink commented on src/test/java/easytests/api/v1/controllers/TopicsControllerTest.java
> +        when(this.topicsService.findBySubject(new SubjectModelEmpty(Integer.valueOf(subjectIdParamValue))))
duplicate 75 row

2018-05-21 19:59 UTC, malinink commented on src/main/java/easytests/api/v1/mappers/TopicsMapper.java
> +            .addMappings(mapper -> mapper.when(
when is not necessary here, remove it

2018-05-21 20:30 UTC, Ielay commented on src/main/java/easytests/api/v1/controllers/TopicsController.java
> +    private TopicsOptionsBuilderInterface topicsOptionsBuilder;
@malinink With what?

2018-05-21 20:36 UTC, Ielay commented on src/main/java/easytests/api/v1/controllers/TopicsController.java
> +import java.util.List;
@malinink Isn't we decide on this after looking on the first character in the path? If so, there is alphabet order: "e", "j" and then "o".
P.s. Checkstyle feels good on this order

2018-05-21 20:42 UTC, Ielay commented on src/main/java/easytests/api/v1/controllers/TopicsController.java
> +import java.util.List;
@malinink Oh... I guess we should look at the first character of the each path layer. Okay.

2018-05-21 20:47 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/97182039-b89b-4820-943c-cf21fea8a0dc) was created.

2018-05-21 20:48 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/db9a2b2b-ac23-47aa-b838-e431f435702e) was created.

2018-05-21 20:52 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/97182039-b89b-4820-943c-cf21fea8a0dc) completed: **3 updated code elements**

2018-05-21 20:55 UTC, Ielay commented
@malinink Fixed all of non-order remarks.

2018-05-21 20:57 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/db9a2b2b-ac23-47aa-b838-e431f435702e) completed: **No new issues**

2018-05-22 07:28 UTC, malinink commented on src/main/java/easytests/api/v1/controllers/TopicsController.java
> +import java.util.List;
Hm.. My Idea tells me that order is wrong, checkstyle does not check test files.
Please look again.
Other seems to be correct!

2018-05-22 11:35 UTC, Ielay commented on src/main/java/easytests/api/v1/controllers/TopicsController.java
> +import java.util.List;
@malinink Ну я правда не знаю, в чем дело. Ни travis, ни локальный checkstyle не видит ошибок.
![image](https://user-images.githubusercontent.com/31778100/40360006-47b7c558-5dcd-11e8-8728-35e6c4b34f22.png)

2018-05-22 21:01 UTC, malinink approved these changes

2018-05-22 21:12 UTC, merged