List method for IssueController
malinink/easy-tests pull request #334
Opened 2018-05-11 07:20 UTC by Yarik2308

https://github.com/malinink/easy-tests/issues/333

- [ ] Method
- [ ] Test

2018-05-11 18:13 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/04bf51bf-5ec2-4e8b-b619-af4a09eb0092) was created.

2018-05-11 18:15 UTC, Yarik2308 commented
@malinink Wait Room for issueSupport.

2018-05-11 18:20 UTC, malinink commented
@Yarik2308 look at PR, it seems you revert back comments.

2018-05-11 18:38 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/7a8b0cca-34e7-40c6-895e-468bd2f8a259) was created.

2018-05-11 18:39 UTC, Yarik2308 commented
@malinink oops... Sorry. I just created this branch before pulling branch with model/mapper etc

2018-05-11 18:40 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/7a8b0cca-34e7-40c6-895e-468bd2f8a259) completed: **1 updated code elements**

2018-05-12 05:45 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/4321f10a-eb2b-4c78-bb9c-105abb7fd4df) was created.

2018-05-12 05:47 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/4321f10a-eb2b-4c78-bb9c-105abb7fd4df) completed: **1 updated code elements**

2018-05-12 07:26 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/94ee076b-3f09-4480-8f62-48a5f9ef779d) was created.

2018-05-12 07:28 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/94ee076b-3f09-4480-8f62-48a5f9ef779d) completed: **1 updated code elements**

2018-05-14 20:29 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/97133207-81c9-4a5c-9791-115515bcd25d) was created.

2018-05-14 20:32 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/97133207-81c9-4a5c-9791-115515bcd25d) completed: **1 updated code elements**

2018-05-15 08:30 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/26c994a3-774e-4df1-8f3e-2a96da564d84) was created.

2018-05-15 08:36 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/26c994a3-774e-4df1-8f3e-2a96da564d84) completed: **2 updated code elements**

2018-05-15 08:58 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/573d9b51-48d8-4780-947b-47ba663a4f7d) was created.

2018-05-15 09:00 UTC, Yarik2308 commented
@malinink test pass in my PC. But without Support class in dev it will not pass here. I can copy it from https://github.com/malinink/easy-tests/issues/237 and before merge delete it.

2018-05-15 09:01 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/573d9b51-48d8-4780-947b-47ba663a4f7d) completed: **2 updated code elements**

2018-05-15 10:28 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/3deb13b9-5f83-4582-a38d-8b9607cff90f) was created.

2018-05-15 10:29 UTC, Yarik2308 commented
@malinink Do i have too test all exceptions in that PR?

2018-05-15 10:34 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/3deb13b9-5f83-4582-a38d-8b9607cff90f) completed: **2 updated code elements**

2018-05-15 10:51 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/de371f6e-f14b-4fd8-ba05-9240c0b9eec5) was created.

2018-05-15 10:54 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/de371f6e-f14b-4fd8-ba05-9240c0b9eec5) completed: **2 updated code elements**

2018-05-15 10:57 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/ad8aafee-2353-401c-b026-8a937eb8738d) was created.

2018-05-15 11:01 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/ad8aafee-2353-401c-b026-8a937eb8738d) completed: **2 updated code elements**

2018-05-15 11:03 UTC, Yarik2308 commented
@malinink Do I have to test Subject not Integer?

2018-05-15 11:05 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/1bc61e79-e556-4855-bf45-257919e0f68d) was created.

2018-05-15 11:06 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/25fb7a27-8173-4df0-b7dc-d50641743e5c) was created.

2018-05-15 11:07 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/1bc61e79-e556-4855-bf45-257919e0f68d) completed: **2 updated code elements**

2018-05-15 11:11 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/8c011c11-07d1-4e38-9bc7-bec27b8cce25) was created.

2018-05-15 11:14 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/8c011c11-07d1-4e38-9bc7-bec27b8cce25) completed: **2 updated code elements**

2018-05-15 15:02 UTC, Yarik2308 commented
@malinink Wait Room for issueSupport.

2018-05-16 17:30 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/2e104399-bc3c-4d70-a1ee-1104a42a13ee) was created.

2018-05-16 17:33 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/2e104399-bc3c-4d70-a1ee-1104a42a13ee) completed: **2 updated code elements**

2018-05-16 20:17 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/cbb920cc-7454-4935-8c84-1d9deac55794) was created.

2018-05-16 20:25 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/462c5a50-a4c3-48fe-bb7c-1afb49e38886) was created.

2018-05-16 20:27 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/989712e2-2bdb-4d5b-b74b-1666f868e874) was created.

2018-05-16 20:33 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/989712e2-2bdb-4d5b-b74b-1666f868e874) completed: **2 updated code elements**

2018-05-16 20:36 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/03aa1952-14bb-4928-bf69-968d864d6d0f) was created.

2018-05-16 20:41 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/03aa1952-14bb-4928-bf69-968d864d6d0f) completed: **2 updated code elements**

2018-05-16 20:51 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/9ada85ee-a27e-4834-b568-3d317da7e3d1) was created.

2018-05-16 20:55 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/9ada85ee-a27e-4834-b568-3d317da7e3d1) completed: **2 updated code elements**

2018-05-16 20:57 UTC, Yarik2308 commented
@malinink Ready for review

2018-05-17 04:49 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/4b67a047-88e5-4c2d-9c97-092c2f4aef3c) was created.

2018-05-17 04:53 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/4b67a047-88e5-4c2d-9c97-092c2f4aef3c) completed: **2 updated code elements**

2018-05-19 10:10 UTC, Yarik2308 commented
@malinink Ready for review

2018-05-21 20:05 UTC, malinink requested changes

2018-05-21 20:05 UTC, malinink commented on src/main/java/easytests/api/v1/controllers/IssuesController.java
> +                .findBySubject(new SubjectModelEmpty(subjectId));
use subjectModel you already have.

2018-05-21 20:05 UTC, malinink commented on src/main/java/easytests/api/v1/mappers/IssuesMapper.java
> +                mapper -> mapper.when(
no need of when

2018-05-22 09:58 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/98cd43d6-3ea9-4eb7-bf42-963dd9f805f4) was created.

2018-05-22 10:04 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/98cd43d6-3ea9-4eb7-bf42-963dd9f805f4) completed: **3 updated code elements**

2018-05-22 10:06 UTC, Yarik2308 commented
@malinink Done.

2018-05-22 11:11 UTC, malinink requested changes

2018-05-22 11:11 UTC, malinink commented on src/main/java/easytests/api/v1/controllers/IssuesController.java
> +import easytests.common.exceptions.NotFoundException;
use not found from v1 package

2018-05-22 11:27 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/e733b51d-5f3e-4cb2-8efe-120dfd1b6b2a) was created.

2018-05-22 11:30 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/e733b51d-5f3e-4cb2-8efe-120dfd1b6b2a) completed: **No new issues**

2018-05-22 11:30 UTC, Yarik2308 commented
@malinink Done (x2).

2018-05-22 20:59 UTC, malinink approved these changes

2018-05-22 20:59 UTC, merged