Add Question Mapper/Model/Controller/ControllerTest
malinink/easy-tests pull request #336
Opened 2018-05-11 18:47 UTC by RisaMagpie

https://github.com/malinink/easy-tests/issues/332

- [x] Add Question Mapper
- [x] Add Question Model
- [x] Add Question Controller
- [x] Add Question ControllerTest
- [x] Add Answer Mapper
- [x] Add Answer Model

2018-05-11 18:48 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/d780c335-c97c-4d6b-b86e-009560370b53) was created.

2018-05-11 18:48 UTC, RisaMagpie commented
Do we need to do Answers Model and Mapper?

2018-05-11 18:52 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/d780c335-c97c-4d6b-b86e-009560370b53) completed: **3 updated code elements**

2018-05-12 17:43 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/1ad6d674-d3b2-46f8-937c-be3128d58717) was created.

2018-05-12 17:47 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/1ad6d674-d3b2-46f8-937c-be3128d58717) completed: **5 updated code elements**

2018-05-12 17:48 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/b10fabe1-d872-44b7-9128-0050358cc78f) was created.

2018-05-12 17:52 UTC, RisaMagpie commented
@malinink all done, coverage decreased=(

2018-05-12 17:52 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/b10fabe1-d872-44b7-9128-0050358cc78f) completed: **5 updated code elements**

2018-05-14 18:16 UTC, malinink requested changes

2018-05-14 18:16 UTC, malinink commented on src/main/java/easytests/api/v1/models/Question.java
> +    private List<Identity> answers;
adminAnswers not Identity

2018-05-15 14:54 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/36dee8f3-4ff8-4c0b-82b7-2fa3eec64071) was created.

2018-05-15 14:54 UTC, RisaMagpie commented
@malinink fixed

2018-05-15 14:59 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/36dee8f3-4ff8-4c0b-82b7-2fa3eec64071) completed: **5 updated code elements**

2018-05-15 18:31 UTC, merged