List method for SubjectsController
malinink/easy-tests pull request #348
Opened 2018-05-17 20:09 UTC by VeronikaRevjakina

#346 

- [ ]  Method

- [ ] TestListSuccess

- [ ] Add ACL

- [ ]  testListNotFound

- [ ] testListForbidden

- [ ] testListUserIdNotInt

2018-05-17 20:09 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/8c9a36d1-95dc-4765-9b45-b595b375661d) was created.

2018-05-17 20:57 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/1017148a-d77f-4746-adc9-3f40a524bf21) was created.

2018-05-17 21:05 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/1017148a-d77f-4746-adc9-3f40a524bf21) completed: **2 updated code elements**

2018-05-17 21:08 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/80da0e55-4841-4fd4-8c9e-b32c31d41e3d) was created.

2018-05-17 21:13 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/80da0e55-4841-4fd4-8c9e-b32c31d41e3d) completed: **2 updated code elements**

2018-05-17 21:48 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/a2374ae7-a2b0-47c3-8d72-ea2a159c3cf2) was created.

2018-05-17 21:53 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/a2374ae7-a2b0-47c3-8d72-ea2a159c3cf2) completed: **2 updated code elements**

2018-05-19 12:28 UTC, greenbarrow commented
@VeronikaRevjakina can you please complete your PR? I need your SubjectsMapper. Maybe i can somehow help you with it?

2018-05-19 13:00 UTC, greenbarrow commented
[checkstyle.zip](https://github.com/malinink/easy-tests/files/2019444/checkstyle.zip)
Try this. Now it gonna be allright. And you also can install checkstyle plugin in ide. In the wiki there information about how to do it.

2018-05-19 13:09 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/45b9b3b8-551a-43bc-9e3b-39bec017f72e) was created.

2018-05-19 13:12 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/45b9b3b8-551a-43bc-9e3b-39bec017f72e) completed: **3 updated code elements**

2018-05-19 13:45 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/63a4455c-f89c-408c-993c-0ed29ec3e3ed) was created.

2018-05-19 13:49 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/63a4455c-f89c-408c-993c-0ed29ec3e3ed) completed: **No new issues**

2018-05-19 13:55 UTC, VeronikaRevjakina commented
@malinink check this PR as fast as you can ,please,because greenbarrow needs Subjects mapper (which I've changed). So there will be conflicts if we change mapper at the same time.

2018-05-20 19:58 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/c3f24649-e3af-43f9-bdaf-94df545b1fd3) was created.

2018-05-20 20:03 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/c3f24649-e3af-43f9-bdaf-94df545b1fd3) completed: **No new issues**

2018-05-21 20:10 UTC, malinink requested changes

2018-05-21 20:10 UTC, malinink commented on src/main/java/easytests/api/v1/controllers/SubjectsController.java
> +        final List<SubjectModelInterface> subjectsModels = this.subjectsService.findByUser(new UserModelEmpty(userId));
Uh, use userModel you have declared in 45 line

2018-05-21 20:10 UTC, malinink commented on src/main/java/easytests/api/v1/mappers/SubjectsMapper.java
> +                mapper -> mapper.when(
do not copy paste code, that you don't understand. When here is not necessary, remove.

2018-05-21 21:43 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/1e7f753c-3efd-4cdb-bc30-a2a37d4fc2b5) was created.

2018-05-21 21:46 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/1e7f753c-3efd-4cdb-bc30-a2a37d4fc2b5) completed: **1 new issues**

2018-05-21 21:50 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/ec29cc28-bc6b-42fc-8f5a-e81933b8f95e) was created.

2018-05-21 21:58 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/ec29cc28-bc6b-42fc-8f5a-e81933b8f95e) completed: **No new issues**

2018-05-21 22:06 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/db4029e6-a665-48b1-823e-1b1fd349e319) was created.

2018-05-21 22:10 UTC, VeronikaRevjakina commented
@malinink improved mistakes,check please

2018-05-21 22:11 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/db4029e6-a665-48b1-823e-1b1fd349e319) completed: **No new issues**

2018-05-22 07:27 UTC, malinink requested changes

2018-05-22 07:27 UTC, malinink commented on src/main/java/easytests/api/v1/controllers/SubjectsController.java
> +import easytests.common.exceptions.NotFoundException;
use v1 NotFound exception

2018-05-22 09:29 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/bbeab2aa-493f-463c-8ff4-e8e0cb7bab2a) was created.

2018-05-22 09:37 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/bbeab2aa-493f-463c-8ff4-e8e0cb7bab2a) completed: **No new issues**

2018-05-22 09:46 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/19e32d5f-5655-4ec7-b68a-97db4d72a40a) was created.

2018-05-22 09:47 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/19e32d5f-5655-4ec7-b68a-97db4d72a40a) completed: **No new issues**

2018-05-22 21:01 UTC, malinink approved these changes

2018-05-22 21:01 UTC, merged