List method for QuizzesController
malinink/easy-tests pull request #364
Opened 2018-05-20 12:11 UTC by miron97

- [ ] list method

- [ ] test list method

- [ ] ACL
#362

2018-05-20 12:12 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/0e6dc2b7-40a8-4d8b-acff-cb7958e75b99) was created.

2018-05-20 12:16 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/0e6dc2b7-40a8-4d8b-acff-cb7958e75b99) completed: **3 updated code elements**

2018-05-20 12:53 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/6b490d88-6cd7-4f8e-9036-9de20d55e4d7) was created.

2018-05-20 12:57 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/6b490d88-6cd7-4f8e-9036-9de20d55e4d7) completed: **No new issues**

2018-05-21 12:29 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/399c0f77-b04a-4c05-845e-6734371dcf57) was created.

2018-05-21 12:34 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/399c0f77-b04a-4c05-845e-6734371dcf57) completed: **8 new issues, 2 updated code elements**

2018-05-21 21:09 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/5c2ce125-5b87-4703-83d5-bf4d415f82e4) was created.

2018-05-21 21:15 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/5c2ce125-5b87-4703-83d5-bf4d415f82e4) completed: **No new issues**

2018-05-21 21:20 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/46153926-6341-4c1c-a6c5-c5db0fe2bade) was created.

2018-05-21 21:25 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/46153926-6341-4c1c-a6c5-c5db0fe2bade) completed: **No new issues**

2018-05-21 21:28 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/6326c74b-439c-4bc4-92e3-73eb07b0a447) was created.

2018-05-21 21:32 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/6326c74b-439c-4bc4-92e3-73eb07b0a447) completed: **No new issues**

2018-05-21 21:47 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/c6a5e202-d5dd-4c8f-9184-1ec4bb55c585) was created.

2018-05-21 21:53 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/c6a5e202-d5dd-4c8f-9184-1ec4bb55c585) completed: **No new issues**

2018-05-21 22:07 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/ed6333c0-96eb-48c4-96fe-e8ecd79c6849) was created.

2018-05-21 22:10 UTC, miron97 commented
@malinink PR ready for review

2018-05-21 22:16 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/ed6333c0-96eb-48c4-96fe-e8ecd79c6849) completed: **No new issues**

2018-05-22 20:21 UTC, malinink requested changes

2018-05-22 20:21 UTC, malinink commented on src/test/java/easytests/api/v1/controllers/QuizzesControllerTest.java
> +                quizzesModels.add(quizModel);
seems that you trying to create list, but than you filter it to 1 element.
make list consist of two items, one with testee included other without it

2018-05-22 20:21 UTC, malinink commented on src/main/java/easytests/api/v1/mappers/QuizzesMapper.java
> +                .addMappings(mapper -> mapper.using(src -> ((LocalDateTime) src.getSource())
how that handle nulls?

2018-05-22 20:21 UTC, malinink commented on src/main/java/easytests/api/v1/mappers/QuizzesMapper.java
> +                        .format(DateTimeFormatter.ISO_LOCAL_DATE_TIME) + Z)
also that

2018-05-22 20:21 UTC, malinink commented on src/test/java/easytests/api/v1/controllers/QuizzesControllerTest.java
> +                quizzesModels.add(quizModel);
Add nulls values (where possible) into test case.

2018-05-23 20:18 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/b94c68ef-7ad2-4058-abc7-5f98b62a4c0b) was created.

2018-05-23 20:21 UTC, miron97 commented
@malinink ready for review

2018-05-24 18:18 UTC, malinink commented
All is OK, but! It seems to me that we forget about Issue model that is linked to Quiz.

@miron97 
Have you time to add it as required field into quiz and add it into model, list method and fix tests?

2018-05-24 21:04 UTC, miron97 commented
@malinink 
Ok, I think it`s not difficult

2018-05-24 21:19 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/d0d76c54-9f0a-4759-bd7b-17bb2929dfd4) was created.

2018-05-24 21:29 UTC, miron97 commented
@malinink ready

2018-05-24 21:35 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/bca5fc74-4e5d-4a44-91bf-fb07951f129a) completed: **1 new issues, 5 updated code elements**

2018-05-25 05:37 UTC, malinink commented
@miron97 Thanks!

2018-05-25 05:38 UTC, malinink approved these changes

2018-05-25 06:38 UTC, merged