Create method for SubjectsController
malinink/easy-tests pull request #379
Opened 2018-05-22 21:24 UTC by VeronikaRevjakina

#358

- [x] Add create method for SubjectsController

- [x] Add checkUser method for SubjectsController

- [x] testCreateSuccess 

- [x] testCreateWithIdFailed

- [x] testCheckUserBadRequest

- [x] testCreateForbidden

2018-05-22 21:28 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/a4e09ddc-647b-4e24-9ce3-80a15ad68dc2) completed: **1 updated code elements**

2018-05-22 21:30 UTC, VeronikaRevjakina commented
@malinink please, check if create method is correct

2018-05-23 19:17 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/e2273bca-5643-422f-b4a8-ac7f2184a194) was created.

2018-05-23 19:21 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/e2273bca-5643-422f-b4a8-ac7f2184a194) completed: **1 updated code elements**

2018-05-23 19:30 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/0937df8b-b6ea-482f-bae4-9981676693f1) was created.

2018-05-23 19:37 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/0937df8b-b6ea-482f-bae4-9981676693f1) completed: **1 updated code elements**

2018-05-23 21:18 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/34be3bb8-cd9a-4099-83c7-4edbdf577057) was created.

2018-05-23 21:21 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/34be3bb8-cd9a-4099-83c7-4edbdf577057) completed: **1 updated code elements**

2018-05-24 14:43 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/4c4a6e43-f2e9-4e19-805c-b937a448c620) completed: **1 updated code elements**

2018-05-24 19:39 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/09077ff9-9894-4334-bdea-65ac2eb3fd68) was created.

2018-05-24 19:43 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/09077ff9-9894-4334-bdea-65ac2eb3fd68) completed: **1 updated code elements**

2018-05-24 20:57 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/cdd7dc0d-4d01-4251-a000-d0ebc4a5d2e3) was created.

2018-05-24 21:02 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/cdd7dc0d-4d01-4251-a000-d0ebc4a5d2e3) completed: **3 updated code elements**

2018-05-24 22:05 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/06ffe25a-d36b-4f10-a976-800f967d8951) was created.

2018-05-25 08:12 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/df05ac98-ebf7-4e6e-a7da-29dbc38acd91) was created.

2018-05-25 08:16 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/df05ac98-ebf7-4e6e-a7da-29dbc38acd91) completed: **3 updated code elements**

2018-05-25 13:33 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/28589f5b-13e6-47c6-b757-65894d1b5599) was created.

2018-05-25 13:40 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/28589f5b-13e6-47c6-b757-65894d1b5599) completed: **3 updated code elements**

2018-05-25 17:29 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/3e04b30e-a9a9-41c7-97f9-87716652e3ee) was created.

2018-05-25 17:33 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/3e04b30e-a9a9-41c7-97f9-87716652e3ee) completed: **3 updated code elements**

2018-05-25 18:57 UTC, VeronikaRevjakina commented
@malinink Can you please check the second mapper and give some advice how to fix it ? Thanks.

2018-05-25 21:20 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/7adf8dac-b189-409e-b9e1-6dea876ea212) was created.

2018-05-25 21:28 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/7adf8dac-b189-409e-b9e1-6dea876ea212) completed: **3 updated code elements**

2018-05-25 21:43 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/b84942ac-ac1d-4690-a2b2-3fc7d54b6e5e) was created.

2018-05-25 21:52 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/b84942ac-ac1d-4690-a2b2-3fc7d54b6e5e) completed: **3 updated code elements**

2018-05-25 23:08 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/bfd9a33e-972c-4be9-b7c0-9e61addb603e) was created.

2018-05-25 23:35 UTC, VeronikaRevjakina commented
I don’t know how to solve this CS error , there is no useless white spaces.

2018-05-26 05:09 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/1351fec8-2491-4116-b7d0-9c419997adfe) was created.

2018-05-26 05:13 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/1351fec8-2491-4116-b7d0-9c419997adfe) completed: **4 updated code elements**

2018-05-26 05:37 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/9fc9dee7-dbec-44f6-92bb-030d006922e1) was created.

2018-05-26 05:41 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/9fc9dee7-dbec-44f6-92bb-030d006922e1) completed: **4 updated code elements**

2018-05-26 06:29 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/4fd2d013-d4b3-47ac-b735-f6bc0a7129ed) was created.

2018-05-26 06:34 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/4fd2d013-d4b3-47ac-b735-f6bc0a7129ed) completed: **4 updated code elements**

2018-05-26 08:15 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/8a09704d-5611-4acf-8e58-8e209b1bb780) was created.

2018-05-26 08:33 UTC, malinink requested changes

2018-05-26 08:33 UTC, malinink commented on src/main/java/easytests/api/v1/controllers/SubjectsController.java
> +                throw new ForbiddenException();
BadRequest

2018-05-26 08:33 UTC, malinink commented on src/main/java/easytests/api/v1/controllers/SubjectsController.java
> +        if (subject.getUser() != null) {
check spec

2018-05-26 08:33 UTC, malinink commented on src/test/java/easytests/api/v1/controllers/SubjectsControllerTest.java
> +                        .with(user, new JsonSupport().with(id,2))
select different userId

2018-05-26 08:33 UTC, malinink commented on src/test/java/easytests/api/v1/controllers/SubjectsControllerTest.java
> +    public void testCreateForbidden() throws Exception {
badrequest

2018-05-26 08:33 UTC, malinink commented on src/test/java/easytests/api/v1/controllers/SubjectsControllerTest.java
> +    public void testCheckUserBadRequest() throws Exception {
remove

2018-05-26 08:46 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/fbcc4006-6e52-4730-958d-9a6bf52ec994) was created.

2018-05-26 08:52 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/fbcc4006-6e52-4730-958d-9a6bf52ec994) completed: **4 updated code elements**

2018-05-26 10:27 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/c9cabdbb-df5d-435b-83fd-96f8fd424cd0) completed: **4 updated code elements**

2018-05-26 11:08 UTC, malinink requested changes

2018-05-26 11:08 UTC, malinink commented on src/main/java/easytests/api/v1/controllers/SubjectsController.java
> +        subjectModel.setUser(usersService.find(subject.getUser().getId()));
forAuth

2018-05-26 11:12 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/bfaf0fde-830f-4425-b5bc-2a2f9127958f) was created.

2018-05-26 11:16 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/bfaf0fde-830f-4425-b5bc-2a2f9127958f) completed: **4 updated code elements**

2018-05-26 11:28 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/c99aa1a8-49f0-4636-b0de-bef14f4d180f) was created.

2018-05-26 11:33 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/c99aa1a8-49f0-4636-b0de-bef14f4d180f) completed: **4 updated code elements**

2018-05-27 13:18 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/45bc8dbb-3eef-4b65-aa96-b7c85b5f2721) was created.

2018-05-27 13:36 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/103b65a3-217d-4f6a-ac53-313d04ad18b7) was created.

2018-05-27 13:41 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/103b65a3-217d-4f6a-ac53-313d04ad18b7) completed: **4 updated code elements**

2018-05-27 13:46 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/a844cc7b-b226-411c-8cbc-09b59336e306) was created.

2018-05-27 13:50 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/a844cc7b-b226-411c-8cbc-09b59336e306) completed: **4 updated code elements**

2018-05-27 15:23 UTC, VeronikaRevjakina commented
@malinink Coverage fails not because of my files :acl and userscontroller. Check,please.

2018-05-27 19:27 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/effedf15-1d9c-41ea-b1a7-7c78c3b4c50e) completed: **4 updated code elements**

2018-05-27 20:05 UTC, malinink approved these changes

2018-05-27 20:05 UTC, merged