Read method for QuestionsController
malinink/easy-tests pull request #380
Opened 2018-05-23 16:02 UTC by RisaMagpie

https://github.com/malinink/easy-tests/issues/370
- [x] Method
- [x] Test

2018-05-23 16:51 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/c96242cb-325b-43f4-ad4d-d29775f8a46b) was created.

2018-05-23 16:56 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/c96242cb-325b-43f4-ad4d-d29775f8a46b) completed: **7 new issues, 3 updated code elements**

2018-05-23 16:56 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/f40b52ba-8e69-4113-b9e2-f679e152d463) was created.

2018-05-24 15:34 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/f0202a0e-20c6-40a8-909b-1c0cfdda70ad) was created.

2018-05-24 16:09 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/9397ac8d-eb1d-43b3-bfb0-1f2eac9eac68) completed: **6 new issues, 4 updated code elements**

2018-05-24 16:52 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/e7becf04-65f7-4d2d-929d-dba03838d963) completed: **6 new issues, 4 updated code elements**

2018-05-24 17:03 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/0db3f2a2-5cdd-4030-a7ea-3ea8fc490fbc) was created.

2018-05-24 17:09 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/0db3f2a2-5cdd-4030-a7ea-3ea8fc490fbc) completed: **6 new issues, 4 updated code elements**

2018-05-24 17:13 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/3800a652-8c7c-4c96-bd33-a5126956158e) was created.

2018-05-24 17:21 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/6d9453ec-5619-4084-98f8-396dfadb383e) was created.

2018-05-24 17:25 UTC, HollowPrincess commented
@malinink DOOOOONE

2018-05-24 17:28 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/6d9453ec-5619-4084-98f8-396dfadb383e) completed: **1 new issues, 4 updated code elements**

2018-05-24 18:12 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/cec17689-b248-4c6d-9ab8-63fe95c594a9) completed: **1 new issues, 4 updated code elements**

2018-05-24 18:31 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/8c8bf3c1-7af1-481d-8956-1c1a9b246655) was created.

2018-05-24 18:37 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/9d9ef6ad-5220-4a67-a7bf-75cea51eaf13) was created.

2018-05-24 18:38 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/8c8bf3c1-7af1-481d-8956-1c1a9b246655) completed: **1 new issues, 4 updated code elements**

2018-05-24 19:50 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/dc22be31-0870-4b0b-88e8-e4ba66d8b4ba) was created.

2018-05-24 19:56 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/dc22be31-0870-4b0b-88e8-e4ba66d8b4ba) completed: **1 new issues, 4 updated code elements**

2018-05-24 19:59 UTC, RisaMagpie commented
@malinink travis is OK, I don't know why coverage can't be completed for so long time, so. please mark it with a "ready for review" label

2018-05-25 09:29 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/b2cff1a8-02b9-450a-9fe5-62f8858880ef) completed: **1 new issues, 4 updated code elements**

2018-05-25 18:47 UTC, malinink requested changes

2018-05-25 18:47 UTC, malinink commented on src/main/java/easytests/api/v1/controllers/QuestionsController.java
> +                (new QuestionsOptions()).withAnswers(new AnswersOptions())
I would prefere to use `this.questionsOptionsBuilder.forAuth()` and than add withAnswers.

2018-05-25 18:47 UTC, malinink commented on src/main/resources/api/api.yaml
> +        type: string
remove spaces

2018-05-25 18:47 UTC, malinink commented on src/test/java/easytests/api/v1/controllers/QuestionsControllerTest.java
> +        when(this.questionsOptionsBuilder.forAuth()).thenReturn(new QuestionsOptions());
take your attention on that mock, now it is not necessary. But when you begin use forAuth you will need to modify it. Think of "how".

2018-05-25 21:33 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/366322a8-c92a-4c74-82b0-be76da2ed835) was created.

2018-05-25 21:37 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/366322a8-c92a-4c74-82b0-be76da2ed835) completed: **1 new issues, 4 updated code elements**

2018-05-25 21:41 UTC, RisaMagpie commented
@malinink done. coverage can't stop again.

2018-05-26 07:44 UTC, malinink approved these changes

2018-05-26 07:44 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/e10b3b8a-529a-4118-9aeb-2f4e7787b527) was created.

2018-05-26 07:48 UTC, merged

2018-05-26 07:52 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/e10b3b8a-529a-4118-9aeb-2f4e7787b527) completed: **1 new issues, 4 updated code elements**