Delete method for ObjectController
malinink/easy-tests pull request #384
Opened 2018-05-24 12:32 UTC by AnyaMaz

#365 
 -[X] Add Delete method
 -[X] Add tests for method

2018-05-24 12:32 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/d78470b1-4089-4b60-aaf3-80239d77a372) was created.

2018-05-24 12:38 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/d78470b1-4089-4b60-aaf3-80239d77a372) completed: **3 updated code elements**

2018-05-24 12:45 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/f88d6ad4-3536-46fb-a345-7faf5a4ce9c2) was created.

2018-05-24 12:49 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/f88d6ad4-3536-46fb-a345-7faf5a4ce9c2) completed: **3 updated code elements**

2018-05-24 12:49 UTC, AnyaMaz commented
@malinink Check this PR please.

2018-05-24 20:45 UTC, malinink requested changes

2018-05-24 20:45 UTC, malinink commented on src/main/java/easytests/api/v1/controllers/SubjectsController.java
> +        this.subjectsService.delete(new SubjectsOptions().withRelations(subjectModel));
Why do you use SubjectOptions like that? There is no need.

2018-05-24 20:45 UTC, malinink commented on src/main/java/easytests/api/v1/controllers/SubjectsController.java
> +    private SubjectModelInterface getSubjectModel(Integer id) throws NotFoundException {
I don't think that getSubjectModel mathod is good for fething it for delete.
Use getSubject as always - for Auth.

And if you want to fetch subject for delete manually pass this.subjectsOptionsBuilder.forDelete() into ` getSubjectModel(Integer id, SubjectsOptionsInterface subjectOpt)` in delete method.

2018-05-24 20:45 UTC, malinink commented on src/main/java/easytests/api/v1/controllers/SubjectsController.java
> +    private SubjectModelInterface getSubjectModel(Integer id, SubjectsOptionsInterface subjectOpt) {
`subjectOpt` is not good variable name

2018-05-24 20:45 UTC, malinink commented on src/test/java/easytests/api/v1/controllers/SubjectsControllerTest.java
> +        when(this.subjectsService.find(any(), any())).thenReturn(subjectModel);
also we need to be ensure that object with specified ID passed into delete method of service.

2018-05-24 22:51 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/9178895b-6b2e-4d98-8b2a-2b33ca86186a) was created.

2018-05-24 23:21 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/7584e73e-49e0-4f78-a4a1-a04bd537c853) was created.

2018-05-24 23:26 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/7584e73e-49e0-4f78-a4a1-a04bd537c853) completed: **1 updated code elements**

2018-05-25 09:56 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/465ef5be-cdd3-4776-ba29-c482b95ef8d5) was created.

2018-05-25 10:01 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/465ef5be-cdd3-4776-ba29-c482b95ef8d5) completed: **1 new issues, 1 updated code elements**

2018-05-25 10:05 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/57e0287e-804e-49a2-9384-7e26ad1cfbc4) was created.

2018-05-25 10:14 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/57e0287e-804e-49a2-9384-7e26ad1cfbc4) completed: **1 new issues, 1 updated code elements**

2018-05-25 12:03 UTC, AnyaMaz commented
@malinink check pr plz

2018-05-25 19:17 UTC, malinink requested changes

2018-05-25 19:17 UTC, malinink commented on src/main/java/easytests/api/v1/controllers/SubjectsController.java
> +        final SubjectModelInterface subjectModel = this.getSubjectModel(subjectId);
get subject model will not fetch it for delete, you need to provide Options to select object for delete.
Select for delete (All topics, questions and etc will be included and linked)
Than, you need call delete with that option.


So:
You need first to get subjects for auth, verify user have access and subjects exists.
Than select subject for delete.
Than delete subject with for delete options.

2018-05-26 03:56 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/ab564c00-6e14-4622-bc81-dee0a8a326f1) was created.

2018-05-26 04:00 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/ab564c00-6e14-4622-bc81-dee0a8a326f1) completed: **3 updated code elements**

2018-05-26 04:06 UTC, AnyaMaz commented
@malinink Rdy For Review

2018-05-26 10:14 UTC, malinink requested changes

2018-05-26 10:14 UTC, malinink commented on src/main/java/easytests/api/v1/controllers/SubjectsController.java
> +        System.err.println("TRALALA");
remove

2018-05-26 10:14 UTC, malinink commented on src/main/java/easytests/api/v1/controllers/SubjectsController.java
> +        final SubjectModelInterface subjectModelforDelete = this.getSubjectModelforDelete(subjectId);
использовать отдельную переменную для опшенов, исподзовать её для получения и удаления

2018-05-26 10:14 UTC, malinink commented on src/test/java/easytests/api/v1/controllers/SubjectsControllerTest.java
> +        final ArgumentCaptor<SubjectModelInterface> argumentCaptor = ArgumentCaptor.forClass(SubjectModelInterface.class);
не нужен

2018-05-26 10:14 UTC, malinink commented on src/test/java/easytests/api/v1/controllers/SubjectsControllerTest.java
> +        when(this.acl.hasAccess(any(SubjectModelInterface.class))).thenReturn(true);
мок на null

2018-05-27 15:46 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/9ce4fc7d-13de-4dd9-88cf-49fac50830c2) was created.

2018-05-27 15:51 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/9ce4fc7d-13de-4dd9-88cf-49fac50830c2) completed: **1 updated code elements**

2018-05-27 20:18 UTC, malinink requested changes

2018-05-27 20:18 UTC, malinink commented on src/main/java/easytests/api/v1/controllers/SubjectsController.java
> +        final SubjectModelInterface subjectModel = this.getSubjectModel(subjectId, subjectsOptionsBuilder.forAuth());
нет необходимости, `this.getSubjectModel(subjectId);` и так выберет forAuth. получается лаконичнее.

2018-05-27 20:18 UTC, malinink commented on src/main/java/easytests/api/v1/controllers/SubjectsController.java
> -    private SubjectModelInterface getSubjectModel(Integer id) throws NotFoundException {
оставьте метод, он пригодится как минимум в update.

2018-05-27 20:18 UTC, malinink commented on src/main/java/easytests/api/v1/controllers/SubjectsController.java
> +                = this.getSubjectModel(subjectId, subjectsOptionsBuilder.forAuth());
да и тут его используйте!

2018-05-27 20:18 UTC, malinink commented on src/main/java/easytests/api/v1/controllers/SubjectsController.java
> +                = this.getSubjectModel(subjectId, subjectsOptionsBuilder.forDelete());
создайте лучге отдельную переменную под SubjectOptions

2018-05-27 20:47 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/ea0eb858-cdf9-430c-bf57-d4451ae98fab) was created.

2018-05-27 20:51 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/ea0eb858-cdf9-430c-bf57-d4451ae98fab) completed: **1 updated code elements**

2018-05-27 23:08 UTC, AnyaMaz commented
@malinink ready for review

2018-05-28 18:20 UTC, malinink requested changes

2018-05-28 18:20 UTC, malinink commented on src/test/java/easytests/api/v1/controllers/SubjectsControllerTest.java
> +        verify(this.subjectsService, times(1)).delete(subjectModel, subjectsOptionsBuilder.forDelete()  );
`subjectsOptionsBuilder.forDelete()` -т.к.  subjectsOptionsBuilder это мок - то метод вернет null.
Я бы создал опшен, настроил его на возвращение в методе forDelete, и проверил что вызывается именно с этим объектом метод delete.

2018-05-28 18:36 UTC, AnyaMaz commented
@malinink check plz

2018-05-28 18:40 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/b2a08541-b436-4963-9d44-3ed8518bc275) completed: **1 updated code elements**

2018-05-29 08:16 UTC, malinink approved these changes

2018-05-29 08:28 UTC, merged