Read method for Users
malinink/easy-tests pull request #386
Opened 2018-05-24 22:22 UTC by Vlasovigor

- [ ] Add method

- [ ] Add test

- [ ] Add exceptions
https://github.com/malinink/easy-tests/issues/326

2018-05-24 22:27 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/ea82e96e-38b2-470f-8a71-d05c10533fd8) completed: **1 updated code elements**

2018-05-24 22:30 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/bf36803a-0ba1-4e69-91a0-01ba564ad2e3) was created.

2018-05-24 22:34 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/bf36803a-0ba1-4e69-91a0-01ba564ad2e3) completed: **1 updated code elements**

2018-05-24 22:35 UTC, Vlasovigor commented
@malinink pls,look

2018-05-25 18:38 UTC, malinink requested changes

2018-05-25 18:38 UTC, malinink commented on src/main/java/easytests/api/v1/controllers/UsersController.java
> +        if (!this.isAdmin()) {
move admin check before user one. We should not tell to none admin users that some user id exists.

2018-05-25 18:38 UTC, malinink commented on src/test/java/easytests/api/v1/controllers/UsersControllerTest.java
> +    public void testShowNotFound() throws Exception {
fix tests, them will fail after order check changes.

2018-05-25 19:15 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/7e421fd1-b69b-4cbf-8499-a6b032c746d3) was created.

2018-05-25 19:20 UTC, Vlasovigor commented
@malinink fixed,look again please

2018-05-25 19:20 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/7e421fd1-b69b-4cbf-8499-a6b032c746d3) completed: **1 updated code elements**

2018-05-26 17:59 UTC, malinink approved these changes

2018-05-26 17:59 UTC, merged