Delete method for Issue
malinink/easy-tests pull request #387
Opened 2018-05-24 23:28 UTC by janchk

#377

2018-05-24 23:29 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/b88a76de-a9c5-4892-9f81-5d9af8553f13) was created.

2018-05-24 23:32 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/b88a76de-a9c5-4892-9f81-5d9af8553f13) completed: **4 updated code elements**

2018-05-25 14:21 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/8d7b4382-2e93-4a96-a028-1dd41020f7f7) was created.

2018-05-25 14:23 UTC, janchk commented
@malinink check pr pls.

2018-05-25 14:29 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/8d7b4382-2e93-4a96-a028-1dd41020f7f7) completed: **1 new issues, 4 updated code elements**

2018-05-25 14:43 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/a1e96abf-a571-4a2b-814a-69ce1cbe784a) was created.

2018-05-25 14:51 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/a1e96abf-a571-4a2b-814a-69ce1cbe784a) completed: **1 new issues, 4 updated code elements**

2018-05-25 19:36 UTC, malinink requested changes

2018-05-25 19:36 UTC, malinink commented on src/main/java/easytests/api/v1/controllers/IssuesController.java
> +        if (issueModel == null) {
already throwen from getIssueModel

2018-05-25 19:36 UTC, malinink commented on src/main/java/easytests/api/v1/controllers/IssuesController.java
> +    private IssueModelInterface getIssueModel(Integer id) throws NotFoundException {
Lets use getIssueModel for retrieve model for read and update.
For delete (cause it is the only one method) we could use direst option object set in delete action.

2018-05-25 19:46 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/7d24f1d5-4fe6-423d-9bf0-2d9a9f2d660a) was created.

2018-05-25 19:48 UTC, janchk commented
@malinink Fixed

2018-05-25 19:53 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/7d24f1d5-4fe6-423d-9bf0-2d9a9f2d660a) completed: **1 new issues, 4 updated code elements**

2018-05-25 20:40 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/dd3b47f1-c2f8-49f3-9d9e-c0975b0d33a4) was created.

2018-05-25 20:47 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/dd3b47f1-c2f8-49f3-9d9e-c0975b0d33a4) completed: **1 new issues, 4 updated code elements**

2018-05-26 08:13 UTC, malinink requested changes

2018-05-26 08:13 UTC, malinink commented on src/main/java/easytests/api/v1/controllers/IssuesController.java
> +        final IssueModelInterface issueModel = getIssueModel(issueId);
this

2018-05-26 08:13 UTC, malinink commented on src/main/java/easytests/api/v1/controllers/IssuesController.java
> +        this.issuesService.find(issueModel.getId(), this.issuesOptions.forDelete());
issuesOptionsBuilder

2018-05-26 08:13 UTC, malinink commented on src/main/java/easytests/api/v1/controllers/IssuesController.java
> +        this.issuesService.delete(issueModel);
need options here

2018-05-26 08:13 UTC, malinink commented on src/test/java/easytests/api/v1/controllers/IssuesControllerTest.java
> +        when(this.issuesService.find(any(), any())).thenReturn(issueModel);
проверить что выбрали объект для авторизации
проверить что этот объект попал в ACL

проверить что выборали объект с forDelete
и убедиться что передали его в delete с опцией forDelete

2018-05-26 08:13 UTC, malinink commented on src/test/java/easytests/api/v1/controllers/IssuesControllerTest.java
> +        when(this.acl.hasAccess(any(IssueModelInterface.class))).thenReturn(true);
установить возвращение ull при получении модели

2018-05-26 12:25 UTC, malinink approved these changes

2018-05-26 12:30 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/8ea7968d-a810-4efe-b5a7-dc2f0aefdae9) completed: **4 updated code elements**

2018-05-26 18:00 UTC, merged