Update method to UsersController
malinink/easy-tests pull request #388
Opened 2018-05-25 09:40 UTC by AnyaMaz

#366 
- [X] Add Update method in UsersController
- [X] Add Tests for Update method

2018-05-25 09:40 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/85d5c193-e313-41cd-940e-6d818b66b86d) was created.

2018-05-25 09:46 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/85d5c193-e313-41cd-940e-6d818b66b86d) completed: **1 new issues, 4 updated code elements**

2018-05-25 10:03 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/283bcd7a-da5a-4294-b869-cdfd47cf2e29) was created.

2018-05-25 10:08 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/283bcd7a-da5a-4294-b869-cdfd47cf2e29) completed: **1 new issues, 4 updated code elements**

2018-05-25 12:03 UTC, AnyaMaz commented
@malinink check pr plz

2018-05-25 19:48 UTC, malinink requested changes

2018-05-25 19:48 UTC, malinink commented on src/main/java/easytests/api/v1/controllers/SubjectsController.java
> +
what delete subjects method doing in update user method PR?

2018-05-25 20:50 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/d692f67d-7f4a-4131-bb09-fa18d661d7e1) was created.

2018-05-25 20:54 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/d692f67d-7f4a-4131-bb09-fa18d661d7e1) completed: **3 updated code elements**

2018-05-25 20:58 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/98ef2044-34e9-4778-a7f4-504a4d578b4c) was created.

2018-05-25 21:00 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/1de64aa2-ce07-42d4-abbf-673ab993d6c0) was created.

2018-05-25 21:04 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/98ef2044-34e9-4778-a7f4-504a4d578b4c) completed: **3 updated code elements**

2018-05-25 21:09 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/1de64aa2-ce07-42d4-abbf-673ab993d6c0) completed: **3 updated code elements**

2018-05-26 04:05 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/7fb23974-9576-419a-a9f0-b6d5f9c41baf) was created.

2018-05-26 04:09 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/7fb23974-9576-419a-a9f0-b6d5f9c41baf) completed: **3 updated code elements**

2018-05-26 04:13 UTC, AnyaMaz commented
@malinink Rdy For Review

2018-05-26 10:08 UTC, malinink requested changes

2018-05-26 10:08 UTC, malinink commented on src/test/java/easytests/api/v1/controllers/UsersControllerTest.java
> +        this.usersSupport.assertEquals(userModel, userModelCaptor.getValue());
Использовать additionalMock из support для отправления запроса, и проверки того что модель попавшая в save еперь уже имееет все понля аналогичные полученной AM.

2018-05-26 10:08 UTC, malinink commented on src/test/java/easytests/api/v1/controllers/UsersControllerTest.java
> +    public void testUpdateWithSubjectsFailed() throws Exception {
удалить

2018-05-26 10:08 UTC, malinink commented on src/test/java/easytests/api/v1/controllers/UsersControllerTest.java
> +        mvc.perform(put("/v1/users")
добавит мок с null

2018-05-27 20:32 UTC, malinink requested changes

2018-05-27 20:32 UTC, malinink commented on src/main/java/easytests/api/v1/controllers/UsersController.java
> +        if (user.getId() == null) {
isAdmin проверка то где?
И тест на forbidden.

2018-05-27 20:32 UTC, malinink commented on src/main/java/easytests/api/v1/controllers/UsersController.java
> +        if (user.getId() == null) {
Разрезолвите ещё конфликты пожалуйста.

2018-05-27 21:38 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/6c6c6d33-45ce-4afa-b005-dd3f8b59c418) was created.

2018-05-27 21:45 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/6c6c6d33-45ce-4afa-b005-dd3f8b59c418) completed: **2 new issues, 1 updated code elements**

2018-05-27 23:09 UTC, AnyaMaz commented
@malinink ready for review

2018-05-27 23:16 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/50f00dbc-6f44-4cb1-a84c-57ec9122da15) was created.

2018-05-27 23:17 UTC, AnyaMaz commented
@malinink ready for review

2018-05-27 23:20 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/50f00dbc-6f44-4cb1-a84c-57ec9122da15) completed: **1 new issues, 1 updated code elements**

2018-05-28 12:34 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/3f10d3ad-8b27-418a-8fbf-dede39cd2d13) was created.

2018-05-28 12:42 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/3f10d3ad-8b27-418a-8fbf-dede39cd2d13) completed: **1 new issues, 1 updated code elements**

2018-05-28 19:49 UTC, merged