Delete method for Users
malinink/easy-tests pull request #389
Opened 2018-05-25 10:27 UTC by Vlasovigor

- [ ] method

- [ ] Test

- [ ] exceptions
https://github.com/malinink/easy-tests/issues/363

2018-05-25 10:28 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/00654caf-f3d4-4f62-899b-b63b49186ab3) was created.

2018-05-25 10:33 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/00654caf-f3d4-4f62-899b-b63b49186ab3) completed: **1 updated code elements**

2018-05-25 10:33 UTC, Vlasovigor commented
@malinink pls,look

2018-05-25 14:55 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/f6c67ef1-9203-4576-bd4b-0587b990010b) was created.

2018-05-25 15:04 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/f6c67ef1-9203-4576-bd4b-0587b990010b) completed: **1 new issues, 3 updated code elements**

2018-05-25 15:10 UTC, Vlasovigor commented
@malinink ready for review

2018-05-25 19:22 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/07349325-0c52-45e8-a9ae-3fb7ccbe1a3c) was created.

2018-05-25 19:27 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/07349325-0c52-45e8-a9ae-3fb7ccbe1a3c) completed: **1 new issues, 3 updated code elements**

2018-05-25 19:44 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/fcee7389-b29a-4846-9097-30fc7b4566a2) was created.

2018-05-25 19:47 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/c6a4c42a-2a64-4ee3-94bc-ee4e5447e5cc) was created.

2018-05-25 19:48 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/fcee7389-b29a-4846-9097-30fc7b4566a2) completed: **1 new issues, 3 updated code elements**

2018-05-25 19:54 UTC, malinink requested changes

2018-05-25 19:54 UTC, malinink commented on src/main/java/easytests/api/v1/controllers/UsersController.java
> +        if (userModel == null) {
already throw in getUserModel

2018-05-25 19:54 UTC, malinink commented on src/main/java/easytests/api/v1/controllers/UsersController.java
> +        this.usersService.delete(userModelForDelete);
No, You should select for delete, and than delete with same option (for delete!)

2018-05-25 19:54 UTC, malinink commented on src/test/java/easytests/api/v1/controllers/UsersControllerTest.java
> +        final UserModelInterface userNotAdminModel = new UserModel();
may be it is a good idea to move mocking current user as admin and as not admin into separate functions in test.
i.e. withAdmin  withNotAdmin and after use that functions in all test methods.

2018-05-25 19:57 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/c6a4c42a-2a64-4ee3-94bc-ee4e5447e5cc) completed: **1 new issues, 3 updated code elements**

2018-05-25 21:42 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/57f1d31b-a727-4585-b500-768d8cbbe0bc) was created.

2018-05-25 21:46 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/57f1d31b-a727-4585-b500-768d8cbbe0bc) completed: **1 new issues, 1 updated code elements**

2018-05-25 21:48 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/9f9f11c9-12cd-4803-9231-3c67c0bedb73) was created.

2018-05-25 21:54 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/47309f2e-efa6-42bc-a8ae-ca88e740999c) was created.

2018-05-25 21:57 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/9f9f11c9-12cd-4803-9231-3c67c0bedb73) completed: **1 new issues, 1 updated code elements**

2018-05-25 22:02 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/47309f2e-efa6-42bc-a8ae-ca88e740999c) completed: **1 updated code elements**

2018-05-25 22:11 UTC, Vlasovigor commented
@malinink ready for review

2018-05-26 00:12 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/716c81d5-c5da-4705-bf03-cd126675edaa) was created.

2018-05-26 00:15 UTC, Vlasovigor commented
@malinink ready for review

2018-05-26 10:33 UTC, malinink requested changes

2018-05-26 10:33 UTC, malinink commented on src/main/java/easytests/api/v1/controllers/UsersController.java
> +        this.usersService.delete(userModel);
for delete option here

2018-05-26 10:33 UTC, malinink commented on src/test/java/easytests/api/v1/controllers/UsersControllerTest.java
> +        final ArgumentCaptor<UserModelInterface> argumentCaptor = ArgumentCaptor.forClass(UserModelInterface.class);
captor not need

2018-05-27 09:12 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/3b10e98c-af46-4d21-94b6-11897700c6b5) was created.

2018-05-27 09:17 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/3b10e98c-af46-4d21-94b6-11897700c6b5) completed: **1 updated code elements**

2018-05-27 09:17 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/87e9f81e-1831-4d0f-a70d-b7962c253a11) was created.

2018-05-27 09:21 UTC, vlasovigor commented
@malinink pls,look

2018-05-27 20:13 UTC, malinink requested changes

2018-05-27 20:13 UTC, malinink commented on src/main/java/easytests/api/v1/controllers/UsersController.java
> +        if (!this.isAdmin()) {
я бы вынес проверку isAdmin в самое начало, логично совсем ничего не делать, если не админ

2018-05-27 20:13 UTC, malinink commented on src/test/java/easytests/api/v1/controllers/UsersControllerTest.java
> +        final UsersOptionsInterface usersOptionsForDelete=new UsersOptions();
откорректируйте код, нет пробелов

2018-05-27 20:13 UTC, malinink commented on src/test/java/easytests/api/v1/controllers/UsersControllerTest.java
> +        final UserModelInterface userModel = new UserModel();
в тесте, после изменений метода и переноса isAdmin в верх, можно будет убрать половину моков.

2018-05-27 20:13 UTC, malinink commented on src/test/java/easytests/api/v1/controllers/UsersControllerTest.java
> +        final UsersOptionsInterface usersOptionsForDelete=new UsersOptions();
cs по пробелам

2018-05-28 12:22 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/f2e71b11-d6ef-4106-b402-3937c247917b) was created.

2018-05-28 12:25 UTC, vlasovigor commented
@malinink pls,look again

2018-05-28 12:34 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/f2e71b11-d6ef-4106-b402-3937c247917b) completed: **1 updated code elements**

2018-05-28 19:11 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/f37ac5b0-5a54-41cb-aca0-d72fa3e3d49a) was created.

2018-05-28 19:11 UTC, malinink approved these changes

2018-05-28 19:21 UTC, merged