Feature 368
malinink/easy-tests pull request #391
Opened 2018-05-25 13:45 UTC by AnyaMaz

- [X] Add Read method
- [X] Add tests for method
- [X] Add acl

2018-05-25 13:45 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/a371579e-fa54-4b57-9008-0d5afb0ef7c1) was created.

2018-05-25 13:51 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/a371579e-fa54-4b57-9008-0d5afb0ef7c1) completed: **5 updated code elements**

2018-05-25 13:53 UTC, AnyaMaz commented
check pr plz

2018-05-25 20:07 UTC, malinink requested changes

2018-05-25 20:07 UTC, malinink commented on src/main/java/easytests/api/v1/controllers/QuizzesController.java
> +        final QuizModelInterface quizModel = this.getQuizModel(
nope, you shold use forAuth to fetch Quiz, that will be good for hasAcces mathod call.
ForAuth should be implemented in `getQuizModel(Integer id)` if there is no such method yet.

2018-05-25 20:07 UTC, malinink commented on src/test/java/easytests/api/v1/controllers/QuizzesControllerTest.java
> +//        final List<TesteeModelInterface> testeesModels = new ArrayList<>();
remove unused code from PR

2018-05-26 04:17 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/8747ca63-60fd-4ea2-879d-e11b3b961f54) was created.

2018-05-26 04:22 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/8747ca63-60fd-4ea2-879d-e11b3b961f54) completed: **6 updated code elements**

2018-05-26 05:03 UTC, AnyaMaz commented
@malinink Rdy For Review

2018-05-26 18:01 UTC, malinink approved these changes

2018-05-26 18:01 UTC, merged