Delete method for Questions
malinink/easy-tests pull request #392
Opened 2018-05-25 14:39 UTC by Vlasovigor

- [ ] Method

- [ ] Test

- [ ] ACL

- [ ] Test ACL

- [ ] Exceptions
https://github.com/malinink/easy-tests/issues/374

2018-05-25 14:39 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/e8708bd4-6e30-44d2-8c7a-d730b94f39e5) was created.

2018-05-25 14:53 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/3d938fb8-3fcb-410b-bb2d-84f5cae106a1) was created.

2018-05-25 14:57 UTC, Vlasovigor commented
@malinink ready for review

2018-05-25 14:59 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/3d938fb8-3fcb-410b-bb2d-84f5cae106a1) completed: **1 new issues, 3 updated code elements**

2018-05-25 19:38 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/ab116cea-22fc-4456-a1f1-a9204dcf6a54) was created.

2018-05-25 19:44 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/ab116cea-22fc-4456-a1f1-a9204dcf6a54) completed: **1 new issues, 3 updated code elements**

2018-05-25 19:53 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/be0a1d83-42bf-4348-a97a-e46b34d8a894) was created.

2018-05-25 19:56 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/b69078bb-a32c-4c75-b481-e5fdde9c0cac) was created.

2018-05-25 19:58 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/8a1f5d94-cd7f-48a3-9349-9424c09f53e3) was created.

2018-05-25 20:01 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/1a482d6d-5d51-4b44-833c-b177d7456a7b) was created.

2018-05-25 20:06 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/1a482d6d-5d51-4b44-833c-b177d7456a7b) completed: **3 updated code elements**

2018-05-25 20:12 UTC, malinink requested changes

2018-05-25 20:12 UTC, malinink commented on src/main/java/easytests/api/v1/controllers/QuestionsController.java
> +        return this.getQuestionModel(id, this.questionsOptionsBuilder.forDelete());
nope

2018-05-25 20:12 UTC, malinink commented on src/main/java/easytests/api/v1/controllers/QuestionsController.java
> +        this.questionsService.delete(questionModel);
nope, that command only delete question. without answers, and deletion will fail on FK constraint.

2018-05-26 00:00 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/f1b4eee7-9aa1-4285-841a-10a8a0189949) was created.

2018-05-26 00:14 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/e3ea70c5-7e18-421a-ae65-f233c10a0678) was created.

2018-05-26 00:18 UTC, Vlasovigor commented
@malinink ready for review

2018-05-26 10:41 UTC, malinink requested changes

2018-05-26 10:41 UTC, malinink commented on src/main/java/easytests/api/v1/controllers/QuestionsController.java
> +        this.answersService.delete(answerModels);
remove

2018-05-26 10:41 UTC, malinink commented on src/main/java/easytests/api/v1/controllers/QuestionsController.java
> +        this.questionsService.delete(questionModel);
use forDelete option

2018-05-26 10:41 UTC, malinink commented on src/test/java/easytests/api/v1/controllers/QuestionsControllerTest.java
> +        final QuestionModelInterface questionModel = this.questionsSupport.getModelFixtureMock(0);
перемудрили, не нужна тут модель

2018-05-27 18:14 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/3018ecdf-d338-4723-8a83-edfde8724624) was created.

2018-05-27 18:19 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/3018ecdf-d338-4723-8a83-edfde8724624) completed: **1 updated code elements**

2018-05-27 18:25 UTC, vlasovigor commented
@malinink pls,look

2018-05-27 18:26 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/26ab3d3d-e555-4838-8691-f9cfc8af2b77) completed: **1 updated code elements**

2018-05-27 20:56 UTC, malinink approved these changes

2018-05-27 20:56 UTC, merged