Add showMe
malinink/easy-tests pull request #393
Opened 2018-05-25 18:23 UTC by janchk

- [x] ShowMe method
- [x] Tests for ShowMe method

2018-05-25 18:23 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/9ee127b5-8b4c-43df-8f64-d9e7e676f1bb) was created.

2018-05-25 18:24 UTC, janchk commented
@malinink check pr pls

2018-05-25 18:27 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/9ee127b5-8b4c-43df-8f64-d9e7e676f1bb) completed: **1 new issues, 5 updated code elements**

2018-05-25 20:18 UTC, malinink requested changes

2018-05-25 20:18 UTC, malinink commented on src/main/java/easytests/api/v1/controllers/UsersController.java
> +        final String userEmail = this.sessionService.getUserModel().getEmail();
what is that code for?

2018-05-25 20:18 UTC, malinink commented on src/main/java/easytests/api/v1/controllers/UsersController.java
> +        final UserModelInterface userModel = this.usersService.findByEmail(userEmail, userOptions);
all thee lines of code are not need here

2018-05-25 20:18 UTC, malinink commented on src/main/java/easytests/api/v1/controllers/UsersController.java
> +        return this.usersMapper.map(userModel, User.class);
use SessionService to retrieve userModel.

2018-05-25 20:18 UTC, malinink commented on src/test/java/easytests/api/v1/controllers/UsersControllerTest.java
> +    public void testShowMeWithSubjectsSuccess() throws Exception {
remove

2018-05-25 20:18 UTC, malinink commented on src/test/java/easytests/api/v1/controllers/UsersControllerTest.java
> +    public void testShowMeFailed() throws Exception {
testShowMeForbidden

2018-05-25 20:53 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/f63a784e-3622-4ec6-a60f-c09276865473) was created.

2018-05-25 20:53 UTC, janchk commented
@malinink Fixed

2018-05-25 20:59 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/f63a784e-3622-4ec6-a60f-c09276865473) completed: **3 new issues, 5 updated code elements**

2018-05-25 21:09 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/b22703c8-e9c3-45e6-bb93-7e703b3d034a) was created.

2018-05-25 21:19 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/b22703c8-e9c3-45e6-bb93-7e703b3d034a) completed: **1 new issues, 5 updated code elements**

2018-05-26 08:19 UTC, malinink requested changes

2018-05-26 08:19 UTC, malinink commented on src/main/java/easytests/api/v1/mappers/UsersMapper.java
> +                    context -> !(context.getSource() instanceof ModelsListEmpty)
не нужен маппинг

2018-05-26 08:19 UTC, malinink commented on src/main/java/easytests/api/v1/models/User.java
> +    @JsonInclude(JsonInclude.Include.NON_NULL)
удалить

2018-05-26 08:19 UTC, malinink commented on src/test/java/easytests/api/v1/controllers/UsersControllerTest.java
> +        when(this.usersService.findByEmail(any(), any())).thenReturn(userModel);
удалить

2018-05-26 08:19 UTC, malinink commented on src/test/java/easytests/api/v1/controllers/UsersControllerTest.java
> +        final UserModelInterface userModel = new UserModel();
отрефакторить (убрать все 3 строки моков)

2018-05-26 08:38 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/453872fd-ec5c-4dd5-886b-c02314cea3ff) was created.

2018-05-26 08:43 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/453872fd-ec5c-4dd5-886b-c02314cea3ff) completed: **1 new issues, 5 updated code elements**

2018-05-26 10:52 UTC, malinink requested changes

2018-05-26 10:52 UTC, malinink commented on src/main/java/easytests/api/v1/models/User.java
> +    private List<Identity> subjects;
remove

2018-05-26 10:52 UTC, malinink commented on src/test/java/easytests/api/v1/controllers/UsersControllerTest.java
> +    private static String subjects = "subjects";
remove

2018-05-26 10:52 UTC, malinink commented on src/test/java/easytests/api/v1/controllers/UsersControllerTest.java
> +                        .with(email, userModel.getEmail())
Provide cehck for isAdmin

2018-05-26 10:52 UTC, malinink commented on src/main/java/easytests/api/v1/mappers/UsersMapper.java
> +                    context -> !(context.getSource() instanceof ModelsListEmpty)
не нужен

2018-05-26 10:56 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/b882c672-b0b2-495b-bda1-db88b14fc3e9) was created.

2018-05-26 11:01 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/b882c672-b0b2-495b-bda1-db88b14fc3e9) completed: **1 new issues, 4 updated code elements**

2018-05-26 12:26 UTC, malinink approved these changes

2018-05-26 12:34 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/0fdd91fe-2519-4257-8c57-616192a92c95) completed: **1 new issues, 4 updated code elements**

2018-05-26 18:02 UTC, merged