Create method for TopicsController
malinink/easy-tests pull request #395
Opened 2018-05-26 01:37 UTC by AnyaMaz

#367 
- [x] Create Method
- [x] Tests sor create method
- [x] Mapping  Topic -> TopicModel

2018-05-26 01:37 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/9c78de5b-9fa5-46c5-800e-d2fef544cc21) was created.

2018-05-26 03:33 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/8322489e-6e9d-4e1d-b643-4ec42e513dfb) was created.

2018-05-26 03:38 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/8322489e-6e9d-4e1d-b643-4ec42e513dfb) completed: **7 updated code elements**

2018-05-26 03:38 UTC, AnyaMaz commented
@malinink Rdy For Review

2018-05-26 05:56 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/38ced04e-b300-45fd-9b2f-38bdc34c4ccd) was created.

2018-05-26 06:00 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/78a7f689-7953-4849-87a7-7f8fcdd2676f) was created.

2018-05-26 06:01 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/38ced04e-b300-45fd-9b2f-38bdc34c4ccd) completed: **4 updated code elements**

2018-05-26 06:03 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/cf2110ce-6c94-425e-aa66-555e2b48b9c3) was created.

2018-05-26 06:04 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/452b6b16-444b-42a1-a25b-78ed99c9cfee) was created.

2018-05-26 06:05 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/9e898e3b-d240-4f34-80e0-97001c420d2e) was created.

2018-05-26 06:08 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/452b6b16-444b-42a1-a25b-78ed99c9cfee) completed: **2 updated code elements**

2018-05-26 06:13 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/9e898e3b-d240-4f34-80e0-97001c420d2e) completed: **2 updated code elements**

2018-05-26 10:23 UTC, malinink requested changes

2018-05-26 10:23 UTC, malinink commented on src/main/java/easytests/api/v1/controllers/TopicsController.java
> +        final TopicModelInterface topicModel = this.topicsMapper.map(topic, TopicModel.class);
checkSubject -> VR

2018-05-26 10:23 UTC, malinink commented on src/test/java/easytests/api/v1/controllers/TopicsControllerTest.java
> +        verify(this.topicsService, times(1)).save(argumentCaptor.capture());
use support class

2018-05-26 10:23 UTC, malinink commented on src/test/java/easytests/api/v1/controllers/TopicsControllerTest.java
> +
add checkSubjects clause case test

2018-05-28 12:55 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/888f367e-ba3f-447a-bf74-61ceee421b53) was created.

2018-05-28 12:58 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/46ae1f25-10f1-499c-a9f7-0921b0489c8e) was created.

2018-05-28 12:58 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/26f4337a-b41f-489d-a605-5eb740aba0fa) was created.

2018-05-28 12:59 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/bb3e16a3-aa61-4e7d-a743-6648cd7e2785) was created.

2018-05-28 13:00 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/ca2d7b80-389c-4c2b-8efb-eedb994b6e42) was created.

2018-05-28 13:02 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/888f367e-ba3f-447a-bf74-61ceee421b53) completed: **2 new issues, 3 updated code elements**

2018-05-28 13:07 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/ca2d7b80-389c-4c2b-8efb-eedb994b6e42) completed: **2 new issues, 3 updated code elements**

2018-05-28 13:13 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/72fc5f62-40e4-432b-8262-8fb29f3b0056) was created.

2018-05-28 13:16 UTC, AnyaMaz commented on src/test/java/easytests/api/v1/controllers/TopicsControllerTest.java
> +        verify(this.topicsService, times(1)).save(argumentCaptor.capture());
done

2018-05-28 13:16 UTC, AnyaMaz commented on src/test/java/easytests/api/v1/controllers/TopicsControllerTest.java
> +
done

2018-05-28 13:20 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/72fc5f62-40e4-432b-8262-8fb29f3b0056) completed: **1 new issues, 3 updated code elements**

2018-05-28 19:02 UTC, malinink requested changes

2018-05-28 19:02 UTC, malinink commented on src/main/java/easytests/api/v1/controllers/TopicsController.java
> +            throw new ForbiddenException();
bad request

2018-05-28 19:02 UTC, malinink commented on src/test/java/easytests/api/v1/controllers/TopicsControllerTest.java
> +//    TopicModelEmpty
remove comment

2018-05-28 19:02 UTC, malinink commented on src/test/java/easytests/api/v1/controllers/TopicsControllerTest.java
> +        this.topicsSupport.assertEquals(argumentCaptor.getValue(), topicAdditionalEntity);
swap values, topicAdditionalEntity is an expected value

2018-05-28 19:32 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/b7bd41a8-0aa9-4b00-b07a-97360e520c74) was created.

2018-05-28 19:33 UTC, AnyaMaz commented
@malinink Ready for review

2018-05-28 19:38 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/b7bd41a8-0aa9-4b00-b07a-97360e520c74) completed: **1 new issues, 3 updated code elements**

2018-05-28 20:08 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/eb25f7e4-5015-40a0-b03a-86cd76ff8d71) was created.

2018-05-28 20:14 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/eb25f7e4-5015-40a0-b03a-86cd76ff8d71) completed: **1 new issues, 3 updated code elements**

2018-05-29 08:25 UTC, malinink approved these changes

2018-05-29 08:30 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/2f4be67f-e9b4-4f56-ad5d-6665c2404fa1) completed: **1 new issues, 3 updated code elements**

2018-05-29 13:45 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/eb3944a1-2044-411f-bc2b-d0d71337b8e2) was created.

2018-05-29 13:52 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/eb3944a1-2044-411f-bc2b-d0d71337b8e2) completed: **1 new issues, 1 updated code elements**

2018-05-30 18:32 UTC, merged