Create method for QuestionController
malinink/easy-tests pull request #396
Opened 2018-05-26 07:38 UTC by SakhPrace

#361 
 -[X] Add Create method in QuestionControl
 -[X] Add tests for method
 -[X] Add validators

2018-05-26 07:38 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/62312398-a070-45a8-b014-c2d347771e5b) was created.

2018-05-26 07:42 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/62312398-a070-45a8-b014-c2d347771e5b) completed: **7 new issues, 10 updated code elements**

2018-05-26 08:18 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/5747ff26-664b-432f-9234-e63006c2f1c1) was created.

2018-05-26 08:26 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/3aca4c32-1c89-4292-bd68-166ad9414e17) was created.

2018-05-26 08:38 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/d0f53e74-34cd-4bb9-a810-773ac7fd5890) was created.

2018-05-26 08:39 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/040521dc-fc89-440e-9017-23867de334a1) was created.

2018-05-26 08:46 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/36961794-6e97-439a-832a-566ec797d692) was created.

2018-05-26 08:56 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/36961794-6e97-439a-832a-566ec797d692) completed: **7 new issues, 10 updated code elements**

2018-05-26 09:27 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/b1ad730e-a6a2-4216-b8aa-808ba0889afa) was created.

2018-05-26 09:31 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/b1ad730e-a6a2-4216-b8aa-808ba0889afa) completed: **7 new issues, 10 updated code elements**

2018-05-26 09:32 UTC, malinink requested changes

2018-05-26 09:32 UTC, malinink commented on src/main/java/easytests/api/v1/controllers/QuestionsController.java
> +        if (question.getAnswers() == null) {
no need

2018-05-26 09:32 UTC, malinink commented on src/main/java/easytests/api/v1/controllers/QuestionsController.java
> +        this.questionsService.save(questionModel);
with answers

2018-05-26 09:32 UTC, malinink commented on src/main/java/easytests/api/v1/mappers/AdminAnswersMapper.java
> +    public AdminAnswersMapper() {
remove if yours

2018-05-26 09:32 UTC, malinink commented on src/main/java/easytests/api/v1/mappers/QuestionsMapper.java
> +        Converter<AdminAnswer, AnswerModel> convertAdminAnswerToAnswerModel
remove

2018-05-26 09:32 UTC, malinink commented on src/main/java/easytests/api/v1/controllers/QuestionsController.java
> +        this.questionsService.save(questionModel);
with answers

2018-05-26 09:32 UTC, malinink commented on src/test/java/easytests/api/v1/controllers/QuestionsControllerTest.java
> +    public void testCreateWithAnswerValidationFailed() throws Exception {
remove

2018-05-27 19:03 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/69dbaf29-5a02-479f-a5cc-b6684e07224a) was created.

2018-05-27 19:07 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/69dbaf29-5a02-479f-a5cc-b6684e07224a) completed: **8 new issues, 10 updated code elements**

2018-05-27 19:42 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/475c210a-abdc-496d-aa36-2a1e03020455) was created.

2018-05-27 19:47 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/794bb02d-f88d-4d15-99f3-13773e89b074) was created.

2018-05-27 19:47 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/475c210a-abdc-496d-aa36-2a1e03020455) completed: **12 new issues, 10 updated code elements**

2018-05-27 19:52 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/794bb02d-f88d-4d15-99f3-13773e89b074) completed: **12 new issues, 10 updated code elements**

2018-05-27 19:57 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/b4ab1f6c-29fe-4287-87ed-8f8c454a963d) was created.

2018-05-27 20:02 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/b4ab1f6c-29fe-4287-87ed-8f8c454a963d) completed: **12 new issues, 10 updated code elements**

2018-05-27 20:06 UTC, SakhPrace commented
@malinink Ready for Review

2018-05-27 20:49 UTC, malinink requested changes

2018-05-27 20:49 UTC, malinink commented on src/main/java/easytests/api/v1/controllers/QuestionsController.java
> +        questionsService.save(questionModel, questionsOptions.withAnswers(answersOptions));
`this.`

2018-05-27 20:49 UTC, malinink commented on src/main/java/easytests/api/v1/controllers/QuestionsController.java
> +        final AnswersOptions answersOptions = new AnswersOptions();
единожды используете, не создавате переменную.

2018-05-27 20:49 UTC, malinink commented on src/main/java/easytests/api/v1/controllers/QuestionsController.java
> +        final QuestionsOptions questionsOptions = new QuestionsOptions();
тут тоже избыток

2018-05-27 20:49 UTC, malinink commented on src/main/java/easytests/api/v1/controllers/QuestionsController.java
> +        if (question.getId() != null) {
минимальную проерку в виде  check метода всеже далаем, и как-минимум проверяем что име доступ к топику.

2018-05-27 20:49 UTC, malinink commented on src/test/java/easytests/api/v1/controllers/QuestionsControllerTest.java
> +        answer1.map(this.answersSupport.getEntityAdditionalMock(0));
цикл, не?

2018-05-27 20:49 UTC, malinink commented on src/test/java/easytests/api/v1/controllers/QuestionsControllerTest.java
> +        topicModel.setId(questionEntity.getTopicId());
чет перемудрили, зачем нам QTM, создайте QM, map-ните её из сущности, которую получите из support.
И засетите в неё лист ответов. Все.

2018-05-27 20:49 UTC, malinink commented on src/test/java/easytests/api/v1/controllers/QuestionsControllerTest.java
> +                                        .with(text, "Answer1text")
можно один ответ оставить, сократим высоту теста

2018-05-27 20:49 UTC, malinink commented on src/test/java/easytests/support/AnswersSupport.java
> +            {
не надо, у так уже откуда -то взялся ещё один forInsert. уберите.

2018-05-27 22:36 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/49af5dae-c317-4912-9c82-dbb0fb1288a0) was created.

2018-05-27 22:41 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/e1eb8752-4a44-4f88-9a4a-4659a735f5b5) was created.

2018-05-27 22:42 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/49af5dae-c317-4912-9c82-dbb0fb1288a0) completed: **10 new issues, 9 updated code elements**

2018-05-27 22:52 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/e1eb8752-4a44-4f88-9a4a-4659a735f5b5) completed: **10 new issues, 9 updated code elements**

2018-05-27 23:23 UTC, SakhPrace commented
@malinink Ready for review

2018-05-28 19:06 UTC, malinink requested changes

2018-05-28 19:06 UTC, malinink commented on src/main/java/easytests/api/v1/controllers/QuestionsController.java
> +        final TopicModelInterface topicModel = this.topicsService
уберите в checkTopic, поглядите на аналогичные методы в других ПР.
Проверка на IdentifiedModelException должна по идее быть первой

2018-05-28 19:06 UTC, malinink commented on src/test/java/easytests/api/v1/controllers/QuestionsControllerTest.java
> +        answer1.map(this.answersSupport.getEntityAdditionalMock(0));
Ну тут то список ответов разных было бы не плохо.

2018-05-28 19:18 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/63781a94-742c-4e5a-9f97-b5c7e76d6697) was created.

2018-05-28 19:28 UTC, SakhPrace commented
@malinink Ready for review

2018-05-28 19:28 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/a13cd04c-43cf-4eed-97b3-7aaac0e5ef21) was created.

2018-05-28 19:33 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/a13cd04c-43cf-4eed-97b3-7aaac0e5ef21) completed: **10 new issues, 11 updated code elements**

2018-05-29 08:27 UTC, malinink approved these changes

2018-05-29 09:01 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/b029f207-a374-43f1-8a5c-3a1167a1f6fc) was created.

2018-05-29 09:07 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/b029f207-a374-43f1-8a5c-3a1167a1f6fc) completed: **10 new issues, 11 updated code elements**

2018-05-29 09:22 UTC, SakhPrace commented
@malinink Resolved

2018-05-30 18:33 UTC, merged