Fix ignoring of properties in QuizModelTest
malinink/easy-tests pull request #398
Opened 2018-05-26 19:11 UTC by greenbarrow

#237 

- [x] Fix ignore prop

2018-05-26 19:12 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/ef9d0010-e933-4700-b6f5-d244951b4a4b) was created.

2018-05-26 19:16 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/ef9d0010-e933-4700-b6f5-d244951b4a4b) completed: **No new issues**

2018-05-26 19:19 UTC, greenbarrow commented
On my machine all tests success.
wtf?

2018-05-26 19:19 UTC, greenbarrow commented
@malinink I need help :'(

2018-05-26 19:29 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/c362d42b-bcc0-45c0-8cfc-31c963679791) completed: **No new issues**

2018-05-26 19:30 UTC, greenbarrow commented
@malinink Konstantin Aleksandrovich, check this PR, please.

2018-05-27 20:23 UTC, malinink requested changes

2018-05-27 20:23 UTC, malinink commented on src/test/java/easytests/core/models/IssueModelTest.java
>      protected ConfigurationBuilder getConfigurationBuilder() {
уберите метод, совсем, он тут более не нужен.

2018-05-27 20:23 UTC, malinink commented on src/test/java/easytests/support/meanbean/models/SubjectModelFactory.java
> +}
EOF добавьте

2018-05-28 10:54 UTC, greenbarrow commented on src/test/java/easytests/core/models/IssueModelTest.java
>      protected ConfigurationBuilder getConfigurationBuilder() {
done

2018-05-28 10:57 UTC, greenbarrow commented on src/test/java/easytests/support/meanbean/models/SubjectModelFactory.java
> +}
done

2018-05-28 11:00 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/c1e6c9ff-c1c0-43dc-ba84-41a18a95b8c9) was created.

2018-05-28 11:05 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/c1e6c9ff-c1c0-43dc-ba84-41a18a95b8c9) completed: **No new issues**

2018-05-28 11:07 UTC, greenbarrow commented
@malinink Konstantin Aleksandrovich, check this PR, please.

2018-05-28 19:08 UTC, malinink approved these changes

2018-05-28 19:08 UTC, merged