Feature 369
malinink/easy-tests pull request #400
Opened 2018-05-27 20:15 UTC by AnyaMaz

#369 
- [X] Add Update method in TopicsController
- [X] Add Tests for Update method

2018-05-27 20:15 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/4f86051c-6eed-4bb1-bdbe-69af90b4dee4) was created.

2018-05-27 20:51 UTC, malinink requested changes

2018-05-27 20:51 UTC, malinink commented on src/main/java/easytests/api/v1/controllers/TopicsController.java
> +
нужен check метод, поглядите как он сделан в subjects.

2018-05-28 11:20 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/81bf69af-6ba1-4bc8-a7b7-bb27c084e9e2) was created.

2018-05-28 11:26 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/81bf69af-6ba1-4bc8-a7b7-bb27c084e9e2) completed: **1 new issues, 5 updated code elements**

2018-05-28 11:31 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/3a603daa-8e70-409a-9a46-0d435b79e825) completed: **1 new issues, 5 updated code elements**

2018-05-28 12:19 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/b5a0047b-320e-431c-b9b5-aebd099bc774) was created.

2018-05-28 18:49 UTC, malinink requested changes

2018-05-28 18:49 UTC, malinink commented on src/main/java/easytests/api/v1/controllers/TopicsController.java
> +            throw new ForbiddenException();
bad request

2018-05-28 18:57 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/9852c390-6bb5-4f8c-9949-5ae8607d345d) was created.

2018-05-28 18:58 UTC, AnyaMaz commented
@malinink check plz

2018-05-28 19:02 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/9852c390-6bb5-4f8c-9949-5ae8607d345d) completed: **1 new issues, 5 updated code elements**

2018-05-28 20:31 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/16093c7d-b741-4a4f-99d9-dafeb6f1f629) was created.

2018-05-28 20:37 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/16093c7d-b741-4a4f-99d9-dafeb6f1f629) completed: **1 new issues, 3 updated code elements**

2018-05-29 08:17 UTC, malinink approved these changes

2018-05-29 08:28 UTC, merged