Update method for QuestionsController
malinink/easy-tests pull request #401
Opened 2018-05-29 07:47 UTC by greenbarrow

#357 

- [x] Update method

- [x] Tests for update method

2018-05-29 07:48 UTC, greenbarrow commented
For now i using mappers from this PR: #361

2018-05-29 10:58 UTC, malinink requested changes

2018-05-29 10:58 UTC, malinink commented on src/main/java/easytests/api/v1/controllers/QuestionsController.java
> +
лишние переводы

2018-05-29 10:58 UTC, malinink commented on src/main/java/easytests/api/v1/controllers/QuestionsController.java
> +        this.checkTopic(question);
проще сначала проверять checkTopic а затем формировать questionModel

2018-05-29 10:58 UTC, malinink commented on src/main/java/easytests/api/v1/controllers/QuestionsController.java
> +        final QuestionModelInterface questionModel = this.getQuestionModel(question.getId());
ну, как минимум мы обновляем question с answers, поэтому и выбирать из базы мы должны аналогичным образом

2018-05-29 10:58 UTC, malinink commented on src/main/java/easytests/api/v1/controllers/QuestionsController.java
> +        this.questionsService.save(questionModel);
и сохранять также

2018-05-29 10:58 UTC, malinink commented on src/test/java/easytests/api/v1/controllers/QuestionsControllerTest.java
> +        this.questionsSupport.assertEquals(questionModel, questionModelCaptor.getValue());
ответы то не проверяются, предлагаю получить списки и валидировать через answersSupport (там есть проверка листов)

2018-05-29 12:51 UTC, greenbarrow commented on src/main/java/easytests/api/v1/controllers/QuestionsController.java
> +
done

2018-05-29 12:55 UTC, greenbarrow commented on src/main/java/easytests/api/v1/controllers/QuestionsController.java
> +        this.checkTopic(question);
В таком случае проверка checkTopic будет выдавать 400, раньше чем в getQuestionModel мы получим 404. Т.к. в моке acl нельзя указать поведение для null.

2018-05-29 13:01 UTC, brarrow commented on src/main/java/easytests/api/v1/controllers/QuestionsController.java
> +        final QuestionModelInterface questionModel = this.getQuestionModel(question.getId());
QuestionModel в данном случае возвращается с ArrayList со всеми элементами AnswerModel данного question.

2018-05-29 13:01 UTC, greenbarrow commented on src/main/java/easytests/api/v1/controllers/QuestionsController.java
> +        this.questionsService.save(questionModel);
Сохраняется, соответственно тоже

2018-05-29 13:06 UTC, greenbarrow commented on src/test/java/easytests/api/v1/controllers/QuestionsControllerTest.java
> +        this.questionsSupport.assertEquals(questionModel, questionModelCaptor.getValue());
Проверяются. В assertEquals мы сверяем листы с моделями ансверов

2018-05-29 13:31 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/703f1d8a-8180-48df-9388-b4e034ee0a4a) completed: **5 updated code elements**

2018-05-29 13:35 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/3b25eba5-147d-4cff-b24e-eeafabe36b2c) was created.

2018-05-29 13:37 UTC, greenbarrow commented
Каждый раз забываю закоммитить, прежде чем пушить :(

2018-05-29 13:42 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/3b25eba5-147d-4cff-b24e-eeafabe36b2c) completed: **5 updated code elements**

2018-05-29 14:51 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/99da4cee-a4b5-4855-acc4-760573e896d6) was created.

2018-05-29 14:57 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/99da4cee-a4b5-4855-acc4-760573e896d6) completed: **7 updated code elements**

2018-05-29 19:38 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/6b825738-dd94-432f-8e8b-b5213466f67b) was created.

2018-05-29 19:44 UTC, greenbarrow commented
@malinink Ready for rewiew.
Исправил проблему с save.

2018-05-29 19:44 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/6b825738-dd94-432f-8e8b-b5213466f67b) completed: **5 updated code elements**

2018-05-29 19:47 UTC, greenbarrow commented on src/test/java/easytests/api/v1/controllers/QuestionsControllerTest.java
> +        verify(this.questionsService, times(1)).save(questionModelCaptor.capture(), questionOptionCaptor.capture());
Мы здесь используем OptionCaptor, нужно ли каким либо образом его проверять? По окончании теста?

2018-05-30 10:20 UTC, malinink commented on src/test/java/easytests/api/v1/controllers/QuestionsControllerTest.java
> +        verify(this.questionsService, times(1)).save(questionModelCaptor.capture(), questionOptionCaptor.capture());
в идеале не должен быть каптор а должен быть объект, или же  `eq(объект)`

2018-05-30 18:34 UTC, malinink commented
Буду благодарен, если разрезолвите конфликты

2018-05-31 09:26 UTC, greenbarrow commented on src/test/java/easytests/api/v1/controllers/QuestionsControllerTest.java
> +        verify(this.questionsService, times(1)).save(questionModelCaptor.capture(), questionOptionCaptor.capture());
Ого, eq() - то, что нужно! Спасибо! Странно, что я не встретил его, когда гуглил пролему с verify. 
Сейчас исправлю и разрезолвлю всё.

2018-06-02 09:52 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/8b322060-3005-41d9-ad0f-f34d12c59ae7) was created.

2018-06-02 09:57 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/malinink/easy-tests/inspections/8b322060-3005-41d9-ad0f-f34d12c59ae7) completed: **1 updated code elements**

2018-06-02 09:59 UTC, greenbarrow commented
@malinink Константин Алекстандрович, ready for rewiew!

2018-06-08 18:31 UTC, malinink approved these changes

2018-06-08 18:31 UTC, merged